<script setup lang="ts">
// Aidi Wealth: clients (households and businesses, US and Nigeria kept apart), metals, advisers and fees, calculator,
// settings. One menu item; everything else is in the sub-menu here.
useHead({ title: 'Wealth management' })
const route = useRoute(); const router = useRouter()
const TABS: [string, string][] = [['overview', 'Overview'], ['clients', 'Clients'], ['metals', 'Gold & metals'], ['firms', 'Advisers & fees'], ['calculator', 'Calculator'], ['settings', 'Settings']]
const tab = computed({ get: () => String(route.query.t ?? 'overview'), set: (v: string) => router.replace({ query: { t: v } }) })
interface Cl { id: string; name: string; kind: string; tag: string | null; country: string; model: string; status: string; kyc_status: string; email: string | null; user_id: string | null; entity: string | null; totals: { net_worth: number; invested: number; cash: number } }
const { data, refresh } = await useFetch<{ providers?: Record<string, boolean>; clients: Cl[]; fees: { id: string; kind: string; period: string | null; amount: number; currency: string; status: string; paid_on: string | null; client: string | null; firm: string | null; note: string | null }[]; metals: Record<string, any>[]; firms: Record<string, any>[]; settings: Record<string, any> }>('/api/wm/overview')
const { data: me } = await useFetch<{ roles: string[] }>('/api/auth/me', { key: 'me' })
const isAdmin = computed(() => !!me.value?.roles.includes('admin'))
const usd = (v: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(v)
const money = (v: number, c: string) => new Intl.NumberFormat('en-US', { style: 'currency', currency: c, maximumFractionDigits: 0 }).format(v)
const MODEL: Record<string, string> = { managed: 'Managed', advisor: 'Adviser-connected', self_directed: 'Self-directed' }
const country = ref<'all' | 'US' | 'NG'>('all')
const clients = computed(() => (data.value?.clients ?? []).filter((c) => country.value === 'all' || c.country === country.value))
const sum = (k: 'net_worth' | 'invested' | 'cash', cc?: string) => (data.value?.clients ?? []).filter((c) => !cc || c.country === cc).reduce((a, c) => a + c.totals[k], 0)
const byModel = computed(() => ['managed', 'advisor', 'self_directed'].map((m) => ({ label: MODEL[m]!, value: Math.round(clients.value.filter((c) => c.model === m).reduce((a, c) => a + c.totals.net_worth, 0)) })).filter((x) => x.value > 0))
const err = (e: unknown) => (e as { data?: { data?: { error?: { message?: string } } } }).data?.data?.error?.message ?? 'Could not save.'
// new client
const nc = reactive({ open: false, name: '', kind: 'individual', country: 'US', model: 'advisor', tag: '', contact_name: '', email: '', phone: '', msg: '' })
async function addClient() { nc.msg = ''; try { const r = await $fetch<{ id: string }>('/api/wm/clients', { method: 'POST', body: { ...nc, open: undefined, msg: undefined } }); nc.open = false; await navigateTo('/wealth-mgmt/clients/' + r.id) } catch (e) { nc.msg = err(e) } }
// metals
const sp = reactive({ gold: null as number | null, silver: null as number | null, msg: '' }); watchEffect(() => { if (data.value) { sp.gold = data.value.settings.gold_usd_oz; sp.silver = data.value.settings.silver_usd_oz } })
async function revalue() { sp.msg = ''; try { const r = await $fetch<{ revalued: number }>('/api/wm/metals/revalue', { method: 'POST', body: { gold: sp.gold || null, silver: sp.silver || null } }); sp.msg = 'Saved. ' + r.revalued + ' holding' + (r.revalued === 1 ? '' : 's') + ' revalued at spot.'; await refresh() } catch (e) { sp.msg = err(e) } }
const metalTotals = computed(() => { let oz = 0, v = 0, c = 0; const g: Record<string, number> = {}; for (const m of data.value?.metals ?? []) { v += m.current_value ?? 0; c += m.cost ?? 0; const metal = m.meta?.metal ?? 'gold'; g[metal] = (g[metal] ?? 0) + Number(m.meta?.ounces ?? 0); oz += Number(m.meta?.ounces ?? 0) } return { oz, v, c, g } })
const hf = reactive({ open: false, edit: null as Record<string, any> | null })
// firms & fees
const ff = reactive({ open: false, id: '', name: '', kind: 'adviser', country: 'US', contact_name: '', email: '', website: '', terms_type: 'percent_of_fee', terms_rate: '' as string | number, terms_amount: '' as string | number, terms_currency: 'USD', terms_frequency: 'annual', notes: '', msg: '' }); const ffile = ref<File | null>(null)
function editFirm(x?: Record<string, any>) { Object.assign(ff, { open: true, id: '', name: '', kind: 'adviser', country: 'US', contact_name: '', email: '', website: '', terms_type: 'percent_of_fee', terms_rate: '', terms_amount: '', terms_currency: 'USD', terms_frequency: 'annual', notes: '', msg: '' }, x ? { ...x, terms_rate: x.terms_rate ?? '', terms_amount: x.terms_amount ?? '' } : {}); ffile.value = null }
async function saveFirm() { const fd = new FormData(); for (const k of ['id', 'name', 'kind', 'country', 'contact_name', 'email', 'website', 'terms_type', 'terms_rate', 'terms_amount', 'terms_currency', 'terms_frequency', 'notes']) fd.append(k, String((ff as Record<string, unknown>)[k] ?? '')); if (ffile.value) fd.append('file', ffile.value)
  try { await $fetch('/api/wm/firms', { method: 'POST', body: fd }); ff.open = false; await refresh() } catch (e) { ff.msg = err(e) } }
async function delFirm() { if (!confirm('Delete ' + ff.name + '?')) return; const fd = new FormData(); fd.append('delete_id', ff.id); await $fetch('/api/wm/firms', { method: 'POST', body: fd }); ff.open = false; await refresh() }
const fe = reactive({ open: false, firm_id: '', kind: 'referral', period: '', amount: '' as string | number, currency: 'USD', note: '', msg: '' })
async function addFee() { try { await $fetch('/api/wm/fees', { method: 'POST', body: { firm_id: fe.firm_id || undefined, kind: fe.kind, period: fe.period, amount: Number(fe.amount), currency: fe.currency, note: fe.note } }); fe.open = false; await refresh() } catch (e) { fe.msg = err(e) } }
async function feeStatus(id: string, status: string) { await $fetch('/api/wm/fees', { method: 'POST', body: { fee_id: id, status } }); await refresh() }
// settings
const cfg = ref<Record<string, any> | null>(null); watchEffect(() => { if (data.value && !cfg.value) cfg.value = JSON.parse(JSON.stringify(data.value.settings)) })
const sm = ref('')
const sc = ref<'US' | 'NG'>('US')
const OPTS: { k: string; group: 'svc' | 'int'; where: 'both' | 'US' | 'NG'; title: string; desc: string; licence?: boolean; key?: string }[] = [
  { k: 'advisor', group: 'svc', where: 'both', title: 'Adviser-connected', desc: 'Refer clients to licensed advisers and platforms; earn referral fees; track their holdings here.' },
  { k: 'self_directed', group: 'svc', where: 'both', title: 'Self-directed', desc: 'Clients use our tools for a monthly subscription and make their own decisions. No recommendations.' },
  { k: 'managed', group: 'svc', where: 'both', title: 'Managed accounts', desc: 'We manage the money in dedicated accounts for an advisory fee.', licence: true },
  { k: 'savings', group: 'int', where: 'both', title: 'Savings plans', desc: 'Fixed-rate savings for self-directed clients, with monthly interest and certificates.', licence: true },
  { k: 'plaid', group: 'int', where: 'US', title: 'Bank linking (Plaid)', desc: 'Clients link their banks to show live balances next to their investments.', key: 'plaid' },
  { k: 'alpaca', group: 'int', where: 'US', title: 'Alpaca', desc: 'US stocks, ETFs and crypto: account opening with KYC, cash, client-placed orders, transfers.', licence: true, key: 'alpaca' },
  { k: 'fincra', group: 'int', where: 'NG', title: 'Fincra', desc: 'Naira and US dollar receiving accounts in the client\'s name, with a wallet balance.', licence: true, key: 'fincra' },
  { k: 'busha', group: 'int', where: 'NG', title: 'Busha', desc: 'Crypto buy and sell in naira, recorded to the client\'s holdings.', licence: true, key: 'busha' }]
const banks = reactive<Record<string, Record<string, string>>>({ US: {}, NG: {} })
watchEffect(() => { const b = (data.value?.settings as { banks?: Record<string, Record<string, string>> } | undefined)?.banks; if (b) { Object.assign(banks.US, b.US ?? {}); Object.assign(banks.NG, b.NG ?? {}) } })
async function saveSettings(confirm_licence = false) { sm.value = ''; try { await $fetch('/api/wm/settings', { method: 'POST', body: { US: { ...cfg.value!.US, fincra: false, busha: false }, NG: { ...cfg.value!.NG, alpaca: false },  advisory_tiers: cfg.value!.advisory_tiers, banks, confirm_licence } }); sm.value = 'Saved.'; await refresh() } catch (e) { const er = e as { statusCode?: number }; if (er.statusCode === 409 && confirm('You are switching on a service that needs a licence (managed accounts, savings or trading). Confirm you hold the licence for it.')) return saveSettings(true); sm.value = err(e) } }
const SW: [string, string, string][] = [['advisor', 'Adviser-connected (referrals)', 'both'], ['self_directed', 'Self-directed (subscription)', 'both'], ['managed', 'Managed accounts (advisory fee, needs RIA / licence)', 'both'], ['plaid', 'Bank linking (Plaid)', 'US'], ['savings', 'Savings plans (needs licence)', 'both'], ['alpaca', 'Alpaca: stocks, ETFs and crypto, wallet (needs licence)', 'US'], ['busha', 'Busha: crypto (needs licence)', 'NG'], ['fincra', 'Fincra: NGN and USD virtual accounts and wallet (needs licence)', 'both']]
</script>
<template>
  <section v-if="data">
    <div class="hd"><div><p class="label">Aidi Wealth</p><h1>Wealth management</h1></div><div class="acts"><button class="btn" @click="nc.open = true">Add a wealth client</button></div></div>
    <nav class="sub"><button v-for="[k, l] in TABS" :key="k" :class="{ on: tab === k }" @click="tab = k">{{ l }}</button></nav>
    <template v-if="tab === 'overview'">
      <div class="kp"><div class="k"><span>Client assets tracked</span><b>{{ usd(sum('net_worth')) }}</b><em>{{ data.clients.length }} client{{ data.clients.length === 1 ? '' : 's' }}</em></div><div class="k"><span>United States</span><b>{{ usd(sum('net_worth', 'US')) }}</b><em>Aidi Wealth LLC</em></div><div class="k"><span>Nigeria</span><b>{{ usd(sum('net_worth', 'NG')) }}</b><em>Aidi Finance Limited</em></div><div class="k"><span>Cash with clients</span><b>{{ usd(sum('cash')) }}</b><em>linked banks and savings</em></div></div>
      <MarketWidget editable />
      <WmAnalytics />
      <div class="two"><div class="card"><DonutChart title="By service model" total-label="Total" currency="USD" :segments="byModel" /></div>
        <div class="card"><h3>Fees due</h3><div v-for="f in data.fees.filter((x) => x.status === 'due').slice(0, 8)" :key="f.id" class="rw"><span>{{ f.client ?? f.firm }} · {{ f.kind }}{{ f.period ? ' · ' + f.period : '' }}</span><b>{{ money(f.amount, f.currency) }}</b></div><p v-if="!data.fees.some((x) => x.status === 'due')" class="mut">No fees due.</p></div></div>
      <div class="card note"><b>What is switched on</b><span v-for="c in ['US', 'NG']" :key="c">{{ c === 'US' ? 'US' : 'Nigeria' }}: {{ SW.filter(([k, , w]) => (w === 'both' || w === c) && data!.settings[c][k]).map(([, l]) => l.replace(/ \(.*\)/, '')).join(', ') || 'nothing yet' }}</span><span class="mut">US and Nigerian clients are run by separate entities and never cross-sold.</span></div>
    </template>
    <template v-else-if="tab === 'clients'">
      <div class="flt"><button v-for="c in ['all', 'US', 'NG']" :key="c" :class="{ on: country === c }" @click="country = c as 'all'">{{ c === 'all' ? 'All' : c === 'US' ? 'United States' : 'Nigeria' }}</button></div>
      <div class="card tc"><table v-if="clients.length" class="table"><thead><tr><th>Client</th><th>Country</th><th>Service</th><th>KYC</th><th>Portal</th><th class="n">Net worth</th></tr></thead><tbody>
        <tr v-for="c in clients" :key="c.id"><td><NuxtLink :to="'/wealth-mgmt/clients/' + c.id"><b>{{ c.name }}</b></NuxtLink><span class="s">{{ c.kind }}{{ c.tag ? ' · ' + c.tag : '' }} · {{ c.status }}</span></td><td>{{ c.country === 'US' ? 'United States' : 'Nigeria' }}</td><td>{{ MODEL[c.model] }}</td><td><span class="st" :class="c.kyc_status">{{ c.kyc_status.replace('_', ' ') }}</span></td><td>{{ c.user_id ? 'Invited' : '—' }}</td><td class="n"><b>{{ usd(c.totals.net_worth) }}</b></td></tr></tbody></table>
        <EmptyState v-else compact icon="wealth" title="No wealth clients yet" text="Add the individuals, families and businesses you handpick. Each is tied to the US or Nigerian entity and only sees their own household."><button class="btn" @click="nc.open = true">Add a wealth client</button></EmptyState></div>
    </template>
    <template v-else-if="tab === 'metals'">
      <div class="kp"><div class="k"><span>Metals value</span><b>{{ usd(metalTotals.v) }}</b><em :class="metalTotals.v >= metalTotals.c ? 'up' : 'dn'">{{ usd(metalTotals.v - metalTotals.c) }} on cost {{ usd(metalTotals.c) }}</em></div><div v-for="(oz, m) in metalTotals.g" :key="m" class="k"><span>{{ String(m).replace(/^./, (x) => x.toUpperCase()) }}</span><b>{{ oz }} oz</b></div>
        <div class="k spot"><span>Spot price (USD/oz)</span><div class="sr"><label>Gold<input v-model.number="sp.gold" type="number" min="0" step="0.01"></label><label>Silver<input v-model.number="sp.silver" type="number" min="0" step="0.01"></label></div><button class="btn sm" @click="revalue">Save and revalue</button><em>{{ sp.msg || (data.settings.spot_as_of ? 'Last set ' + data.settings.spot_as_of : 'Holdings valued from the dealer statement use their own value.') }}</em></div></div>
      <div class="card tc"><div class="ch"><h3>Gold &amp; metals (group and clients)</h3><button class="btn secondary sm" @click="hf.open = true; hf.edit = null">Add metal</button></div>
        <table class="table"><thead><tr><th>Item</th><th>Belongs to</th><th>Ounces</th><th>Dealer · storage</th><th class="n">Cost</th><th class="n">Value</th><th /></tr></thead><tbody>
          <tr v-for="m in data.metals" :key="m.id"><td><b>{{ m.name }}</b><span class="s">{{ m.meta?.metal }} · {{ m.meta?.quantity ?? '—' }} piece(s) · valued {{ m.meta?.valuation === 'spot' ? 'at spot' : 'from statement' }} · {{ m.as_of }}</span></td><td>{{ m.client ?? 'Group' }}</td><td>{{ m.meta?.ounces ?? '—' }}</td><td>{{ [m.meta?.dealer ?? m.platform, m.meta?.vault].filter(Boolean).join(' · ') }}<span v-if="m.meta?.certificate" class="s">Cert. {{ m.meta.certificate }}</span></td><td class="n">{{ m.cost != null ? money(m.cost, m.currency) : '—' }}</td><td class="n"><b>{{ m.current_value != null ? money(m.current_value, m.currency) : '—' }}</b></td><td><button class="lk" @click="hf.open = true; hf.edit = { ...m, cost: m.cost, current_value: m.current_value }">Edit</button></td></tr></tbody></table></div>
      <AppModal :open="hf.open" :title="hf.edit ? 'Edit metal holding' : 'Add a metal holding (group)'" wide @close="hf.open = false"><HoldingForm :key="hf.edit?.id ?? 'new'" :client-id="hf.edit?.wm_client_id ?? null" :edit="hf.edit ?? { category: 'precious_metals', meta: { dealer: 'APMEX', vault: 'APMEX Citadel vault', valuation: 'manual' } }" @saved="hf.open = false; refresh()" @close="hf.open = false" /></AppModal>
    </template>
    <template v-else-if="tab === 'firms'">
      <div class="card tc"><div class="ch"><h3>Advisers and platforms we refer to</h3><button class="btn secondary sm" @click="editFirm()">Add a firm</button></div>
        <table v-if="data.firms.length" class="table"><thead><tr><th>Firm</th><th>Country</th><th>Our referral terms</th><th>Clients</th><th /></tr></thead><tbody>
          <tr v-for="x in data.firms" :key="x.id"><td><b>{{ x.name }}</b><span class="s">{{ x.kind }}{{ x.contact_name ? ' · ' + x.contact_name : '' }}</span></td><td>{{ x.country ?? '—' }}</td><td>{{ x.terms_type === 'percent_of_fee' ? (x.terms_rate ?? '?') + '% of their fee' : money(x.terms_amount ?? 0, x.terms_currency) + ' flat' }} · {{ x.terms_frequency.replace('_', '-') }}<span v-if="x.agreement_doc_id" class="s">Agreement on file</span></td><td>{{ x.clients }}</td><td><button class="lk" @click="editFirm(x)">Edit</button></td></tr></tbody></table>
        <p v-else class="mut pad">Add each firm with the referral terms in your agreement: a percentage of their fee, or a flat amount.</p></div>
      <div class="card tc"><div class="ch"><h3>Fees</h3><button class="btn secondary sm" @click="Object.assign(fe, { open: true, firm_id: '', kind: 'referral', period: '', amount: '', currency: 'USD', note: '', msg: '' })">Record a fee</button></div>
        <table v-if="data.fees.length" class="table"><thead><tr><th>From</th><th>Type</th><th>Period</th><th class="n">Amount</th><th>Status</th><th /></tr></thead><tbody>
          <tr v-for="f in data.fees" :key="f.id"><td>{{ f.client ?? f.firm }}</td><td>{{ f.kind }}</td><td>{{ f.period ?? '—' }}</td><td class="n">{{ money(f.amount, f.currency) }}</td><td><span class="st" :class="f.status">{{ f.status }}{{ f.paid_on ? ' ' + f.paid_on : '' }}</span></td><td><button v-if="f.status !== 'paid'" class="lk" @click="feeStatus(f.id, 'paid')">Mark paid</button><button v-else class="lk" @click="feeStatus(f.id, 'due')">Undo</button></td></tr></tbody></table>
        <p v-else class="mut pad">Subscription, advisory and referral fees. Marking one paid posts it to the books of Aidi Wealth LLC (US) or Aidi Finance Limited (Nigeria).</p></div>
      <AppModal :open="ff.open" :title="ff.id ? 'Edit firm' : 'Add a firm'" wide @close="ff.open = false"><div class="fm"><div class="g3"><label>Name<input v-model="ff.name" maxlength="200"></label><label>Type<select v-model="ff.kind"><option value="adviser">Adviser</option><option value="platform">Platform</option><option value="dealer">Dealer</option><option value="other">Other</option></select></label><label>Country<select v-model="ff.country"><option value="US">United States</option><option value="NG">Nigeria</option></select></label>
          <label>Contact<input v-model="ff.contact_name"></label><label>Email<input v-model="ff.email"></label><label>Website<input v-model="ff.website"></label>
          <label>Referral terms<select v-model="ff.terms_type"><option value="percent_of_fee">% of their fee</option><option value="flat">Flat amount</option></select></label><label v-if="ff.terms_type === 'percent_of_fee'">Rate %<input v-model="ff.terms_rate" type="number" min="0" step="0.01"></label><label v-else>Amount<input v-model="ff.terms_amount" type="number" min="0"></label><label>Paid<select v-model="ff.terms_frequency"><option value="one_off">One-off</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annual">Yearly</option></select></label></div>
        <label>Referral agreement (PDF)<DropZone compact accept=".pdf" @change="ffile = ($event.target as HTMLInputElement).files?.[0] ?? null" /></label><label>Notes<textarea v-model="ff.notes" rows="2" /></label><p v-if="ff.msg" class="error">{{ ff.msg }}</p></div>
        <template #foot><button v-if="ff.id && isAdmin" class="btn secondary danger" @click="delFirm">Delete</button><button class="btn secondary" @click="ff.open = false">Cancel</button><button class="btn" :disabled="!ff.name" @click="saveFirm">Save</button></template></AppModal>
      <AppModal :open="fe.open" title="Record a referral fee" @close="fe.open = false"><div class="fm"><label>Firm<select v-model="fe.firm_id"><option value="">Choose</option><option v-for="x in data.firms" :key="x.id" :value="x.id">{{ x.name }}</option></select></label><div class="g3"><label>Period<input v-model="fe.period" placeholder="e.g. Q4 2026"></label><label>Amount<input v-model="fe.amount" type="number" min="0"></label><label>Currency<select v-model="fe.currency"><option>USD</option><option>NGN</option></select></label></div><label>Note<input v-model="fe.note"></label><p v-if="fe.msg" class="error">{{ fe.msg }}</p></div>
        <template #foot><button class="btn secondary" @click="fe.open = false">Cancel</button><button class="btn" :disabled="!fe.firm_id || fe.amount === ''" @click="addFee">Save</button></template></AppModal>
    </template>
    <WealthCalculator v-else-if="tab === 'calculator'" />
    <template v-else-if="tab === 'settings' && cfg">
      <p v-if="!isAdmin" class="mut">Only admins can change these settings.</p>
      <div class="cset">
        <div class="ctab"><button v-for="c in (['US', 'NG'] as const)" :key="c" :class="{ on: sc === c }" @click="sc = c"><b>{{ c === 'US' ? 'United States' : 'Nigeria' }}</b><span>{{ c === 'US' ? 'Aidi Wealth LLC' : 'Aidi Finance Limited' }}</span></button></div>
        <p class="mut note">US and Nigerian clients are run by separate entities and never cross-sold. Each country has its own services, products and pricing.</p>
        <div class="card blk"><h3>Services you offer</h3>
          <label v-for="o in OPTS.filter((x) => x.group === 'svc' && (x.where === 'both' || x.where === sc))" :key="o.k" class="opt"><span class="tx"><b>{{ o.title }} <i v-if="o.licence" class="lic">Needs licence</i></b><em>{{ o.desc }}</em></span><span class="tg"><input v-model="cfg[sc][o.k]" type="checkbox" :disabled="!isAdmin"><i /></span></label></div>
        <div class="card blk"><h3>Products and integrations</h3>
          <label v-for="o in OPTS.filter((x) => x.group === 'int' && (x.where === 'both' || x.where === sc))" :key="o.k" class="opt"><span class="tx"><b>{{ o.title }} <i v-if="o.licence" class="lic">Needs licence</i><i v-if="o.key" class="ks" :class="{ ok: data.providers?.[o.key] }">{{ data.providers?.[o.key] ? 'Connected' : 'Keys not set' }}</i></b><em>{{ o.desc }}</em></span><span class="tg"><input v-model="cfg[sc][o.k]" type="checkbox" :disabled="!isAdmin"><i /></span></label>
          <p class="mut">A switch only works once the provider is connected (its keys are set in the server settings).</p></div>
        <div class="two"><div class="card blk"><h3>Pricing</h3>
            <label class="fld">Subscription, self-directed clients<span class="in"><em>{{ cfg[sc].currency }}</em><input v-model.number="cfg[sc].subscription" type="number" min="0" :disabled="!isAdmin"><em>/ month</em></span><small>Typical premium wealth tools charge $30–$100 a month. Suggested: {{ sc === 'US' ? '$49' : '₦25,000' }}.</small></label>
            <label class="fld">Paid online with<span class="ro">{{ sc === 'US' ? 'Stripe' : 'Paystack' }} <i class="ks" :class="{ ok: sc === 'US' ? data.providers?.stripe : data.providers?.paystack }">{{ (sc === 'US' ? data.providers?.stripe : data.providers?.paystack) ? 'Connected' : 'Keys not set' }}</i></span></label></div>
          <div class="card blk" :class="{ dim: !cfg[sc].savings }"><h3>Savings plans</h3>
            <label class="fld">Held with<select v-model="cfg[sc].savings_provider" :disabled="!isAdmin"><option v-if="sc === 'US'" value="alpaca">Alpaca</option><option v-if="sc === 'NG'" value="busha">Busha</option><option value="manual">Another vendor (recorded manually)</option></select></label>
            <label v-if="cfg[sc].savings_provider === 'manual'" class="fld">Vendor<input v-model="cfg[sc].savings_vendor" :disabled="!isAdmin" placeholder="e.g. Cowrywise (Sprout)"></label>
            <label class="fld">Interest rate<span class="in"><input v-model.number="cfg[sc].savings_rate" type="number" min="0" step="0.01" :disabled="!isAdmin"><em>% a year</em></span></label>
            <small class="mut">{{ cfg[sc].savings ? 'For self-directed clients; interest is credited monthly.' : 'Switched off. Turn on "Savings plans" above to offer it.' }}</small></div></div>
        <div class="card blk"><h3>Bank account for advisory fees</h3><p class="mut">Printed on advisory fee invoices; clients pay by bank transfer to {{ sc === 'US' ? 'Aidi Wealth LLC' : 'Aidi Finance Limited' }}.</p>
          <div class="g3"><label v-for="[k, l] in (sc === 'US' ? [['bank', 'Bank'], ['account_name', 'Account name'], ['account_number', 'Account number'], ['routing', 'Routing (ACH)'], ['swift', 'Wire / SWIFT'], ['address', 'Bank address']] : [['bank', 'Bank'], ['account_name', 'Account name'], ['account_number', 'Account number'], ['swift', 'SWIFT (for USD)']])" :key="sc + k" class="fld">{{ l }}<input v-model="banks[sc][k]" :disabled="!isAdmin"></label></div></div>
      </div>
      <div class="card blk"><h3>Advisory fee for managed accounts <span class="mut sm">(both countries)</span></h3><p class="mut">Charged on assets under management; each slice at its own rate, billed quarterly.</p>
        <div v-for="(t, i) in cfg.advisory_tiers" :key="i" class="tier"><span>{{ i === 0 ? 'First' : i === cfg.advisory_tiers.length - 1 ? 'Above that' : 'Next, up to' }}</span><span class="in"><em>$</em><input v-model.number="t.upto" type="number" min="0" :disabled="!isAdmin || i === cfg.advisory_tiers.length - 1" :placeholder="i === cfg.advisory_tiers.length - 1 ? 'no limit' : ''"></span><span>at</span><span class="in"><input v-model.number="t.pct" type="number" min="0" max="5" step="0.05" :disabled="!isAdmin"><em>%</em></span></div></div>
      <div v-if="isAdmin" class="savebar"><span class="mut">{{ sm || 'Changes apply to new clients, invoices and switches straight away.' }}</span><button class="btn" @click="saveSettings()">Save settings</button></div>
    </template>
    <AppModal :open="nc.open" title="Add a wealth client" wide @close="nc.open = false"><div class="fm"><div class="g3"><label>Name *<input v-model="nc.name" maxlength="200" placeholder="Person, family or business"></label><label>Type<select v-model="nc.kind"><option value="individual">Individual</option><option value="family">Family</option><option value="business">Business</option></select></label><label>Tag<input v-model="nc.tag" maxlength="60" placeholder="One name to group them"></label>
        <label>Country<select v-model="nc.country"><option value="US">United States (Aidi Wealth LLC)</option><option value="NG">Nigeria (Aidi Finance Limited)</option></select></label><label>Service<select v-model="nc.model"><option value="advisor">Adviser-connected</option><option value="self_directed">Self-directed (subscription)</option><option value="managed">Managed (advisory fee)</option></select></label><span />
        <label>Main contact<input v-model="nc.contact_name"></label><label>Email<input v-model="nc.email" type="email"></label><label>Phone<input v-model="nc.phone"></label></div><p v-if="nc.msg" class="error">{{ nc.msg }}</p></div>
      <template #foot><button class="btn secondary" @click="nc.open = false">Cancel</button><button class="btn" :disabled="!nc.name" @click="addClient">Add client</button></template></AppModal>
  </section>
</template>
<style scoped>
.hd { display: flex; justify-content: space-between; align-items: flex-end; } .hd h1 { margin: 0; } .sub { display: flex; gap: 4px; background: var(--c-paper-2); padding: 4px; margin: 14px 0; width: fit-content; max-width: 100%; overflow-x: auto; } .sub button { background: none; border: 0; padding: 8px 14px; font: inherit; font-size: 14px; cursor: pointer; white-space: nowrap; } .sub .on { background: #fff; font-weight: 600; box-shadow: 0 1px 3px rgba(12,26,46,.08); }
.kp { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 12px; margin-bottom: 12px; } .k { background: #fff; border: 1px solid var(--c-rule); padding: 12px 14px; display: flex; flex-direction: column; gap: 3px; } .k span { font-size: 12.5px; color: var(--c-muted); } .k b { font-size: 22px; } .k em { font-style: normal; font-size: 12px; color: var(--c-muted); } .k em.up { color: var(--c-ok); } .k em.dn { color: var(--c-danger); }
.spot .sr { display: flex; gap: 8px; } .spot label { display: flex; flex-direction: column; font-size: 12px; color: var(--c-muted); } .spot input { width: 110px; font: inherit; font-size: 13.5px; padding: 5px 7px; border: 1px solid var(--c-rule-strong); } .spot .btn { align-self: flex-start; margin-top: 4px; }
.two { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); gap: 12px; } .two h3, .ch h3 { margin: 0; font-size: 15px; } .rw { display: flex; justify-content: space-between; padding: 7px 0; border-top: 1px solid var(--c-rule); font-size: 13.5px; } .mut { color: var(--c-muted); font-size: 13px; } .pad { padding: 14px; margin: 0; }
.note { display: flex; flex-direction: column; gap: 4px; margin-top: 12px; font-size: 13.5px; } .flt { display: flex; gap: 6px; margin-bottom: 10px; } .flt button { background: #fff; border: 1px solid var(--c-rule); padding: 6px 12px; font: inherit; font-size: 13px; cursor: pointer; } .flt .on { border-color: var(--c-blue-deep); color: var(--c-blue-deep); font-weight: 600; }
.tc { padding: 0; overflow-x: auto; margin-bottom: 12px; } .ch { display: flex; justify-content: space-between; align-items: center; padding: 12px 14px; } .table { width: 100%; border-collapse: collapse; font-size: 13.5px; } .table th { text-align: left; padding: 10px 14px; white-space: nowrap; } .table td { padding: 11px 14px; border-bottom: 1px solid var(--c-rule); vertical-align: top; } .n { text-align: right; white-space: nowrap; } .s { display: block; font-size: 12.5px; color: var(--c-muted); }
td a { color: inherit; text-decoration: none; } .lk { background: none; border: 0; color: var(--c-blue-deep); cursor: pointer; font: inherit; font-size: 12.5px; padding: 0; } .st { font-size: 12px; padding: 2px 8px; background: var(--c-paper-2); text-transform: capitalize; } .st.verified, .st.paid { background: rgba(31,122,77,.1); color: var(--c-ok); } .st.failed { background: rgba(180,35,24,.07); color: var(--c-danger); } .st.pending, .st.due { background: rgba(181,71,8,.09); color: var(--c-warn); }
.fm, .fm * { box-sizing: border-box; } .fm { display: flex; flex-direction: column; gap: 10px; } .g3 { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 10px; } .g2 { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px; margin-top: 8px; } label { display: flex; flex-direction: column; gap: 4px; font-size: 12.5px; color: var(--c-muted); } .fm input, .fm select, .fm textarea, .g2 input, .g2 select { font: inherit; font-size: 14px; padding: 7px 9px; border: 1px solid var(--c-rule-strong); background: #fff; width: 100%; min-width: 0; }
.sg { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); gap: 12px; margin-bottom: 12px; } .sg h3 { margin: 0 0 8px; font-size: 15px; } .sw { flex-direction: row; align-items: center; gap: 8px; font-size: 13.5px; color: var(--c-ink); padding: 3px 0; } .sw input { width: auto; }
.tier { display: flex; gap: 8px; align-items: center; margin: 6px 0; font-size: 13.5px; } .tier input { width: 140px; font: inherit; padding: 6px 8px; border: 1px solid var(--c-rule-strong); } .acts2 { display: flex; gap: 10px; align-items: center; margin-top: 12px; } .error { color: var(--c-danger); }
@media (max-width: 900px) { .two, .sg, .g3 { grid-template-columns: 1fr; } }
.cset { display: flex; flex-direction: column; gap: 12px; } .ctab { display: grid; grid-template-columns: 1fr 1fr; gap: 0; border: 1px solid var(--c-rule); background: #fff; max-width: 560px; }
.ctab button { background: none; border: 0; padding: 12px 16px; text-align: left; cursor: pointer; font: inherit; display: flex; flex-direction: column; gap: 2px; border-bottom: 3px solid transparent; } .ctab button b { font-size: 14.5px; } .ctab button span { font-size: 12px; color: var(--c-muted); } .ctab button.on { border-bottom-color: var(--c-blue-deep); background: var(--c-signal-soft); }
.note { margin: -4px 0 0; } .blk h3 { margin: 0 0 6px; font-size: 15px; } .blk.dim { opacity: .75; } .sm { font-size: 12px; font-weight: 400; }
.opt { display: flex; flex-direction: row !important; justify-content: space-between; align-items: center !important; gap: 16px; padding: 12px 0; border-top: 1px solid var(--c-rule); cursor: pointer; color: var(--c-ink) !important; text-align: left; } .opt .tx { align-items: flex-start; } .opt .tx { display: flex; flex-direction: column; gap: 3px; } .opt .tx b { font-size: 14px; display: flex; gap: 8px; align-items: center; flex-wrap: wrap; } .opt .tx em { font-style: normal; font-size: 12.5px; color: var(--c-muted); max-width: 640px; }
.lic { font-style: normal; font-size: 11px; font-weight: 500; padding: 1px 7px; background: rgba(181,71,8,.09); color: var(--c-warn); } .ks { font-style: normal; font-size: 11px; font-weight: 500; padding: 1px 7px; background: var(--c-paper-2); color: var(--c-muted); } .ks.ok { background: rgba(31,122,77,.1); color: var(--c-ok); }
.tg { position: relative; flex: none; width: 40px; height: 22px; } .tg input { position: absolute; inset: 0; opacity: 0; margin: 0; cursor: pointer; z-index: 1; } .tg i { position: absolute; inset: 0; background: #cfd4da; border-radius: 22px; transition: background .15s; } .tg i::after { content: ''; position: absolute; left: 3px; top: 3px; width: 16px; height: 16px; border-radius: 50%; background: #fff; transition: transform .15s; box-shadow: 0 1px 2px rgba(0,0,0,.2); } .tg input:checked + i { background: var(--c-blue-deep); } .tg input:checked + i::after { transform: translateX(18px); } .tg input:disabled + i { opacity: .5; }
.fld { display: flex; flex-direction: column; gap: 5px; font-size: 12.5px; color: var(--c-muted); margin-top: 10px; } .fld input, .fld select { font: inherit; font-size: 14px; padding: 8px 10px; border: 1px solid var(--c-rule-strong); background: #fff; color: var(--c-ink); } .fld small { font-size: 12px; } .ro { font-size: 14px; color: var(--c-ink); display: flex; gap: 8px; align-items: center; }
.in { display: flex; align-items: center; border: 1px solid var(--c-rule-strong); background: #fff; } .in em { font-style: normal; font-size: 13px; color: var(--c-muted); padding: 0 8px; } .in input { border: 0 !important; flex: 1; min-width: 0; outline: none; padding: 8px 6px; font: inherit; font-size: 14px; }
.two { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); gap: 12px; } .g3 { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 10px; }
.tier { display: grid; grid-template-columns: 110px 200px 30px 120px; gap: 8px; align-items: center; margin: 8px 0; font-size: 13.5px; } .tier .in input { width: 100%; }
.savebar { position: sticky; bottom: 0; display: flex; justify-content: space-between; align-items: center; gap: 12px; background: #fff; border: 1px solid var(--c-rule); padding: 10px 14px; margin-top: 12px; box-shadow: 0 -4px 12px rgba(12,26,46,.05); }
@media (max-width: 900px) { .two, .g3 { grid-template-columns: 1fr; } .tier { grid-template-columns: 1fr 1fr; } }
</style>
