-- 040_directory_tracker.sql — shared investor directory (one row per normalised name), which workspaces use each name;
-- ordered service codes on jobs; the Tracker page for the services desk.
BEGIN;
CREATE OR REPLACE FUNCTION crm.name_key(n text) RETURNS text LANGUAGE sql IMMUTABLE AS $f$
  SELECT trim(regexp_replace(regexp_replace(regexp_replace(lower(replace(n, '&', ' and ')), '[^a-z0-9 ]+', ' ', 'g'), '\m(ltd|llc|inc|limited|plc|lp|llp|gmbh|sa|sas|bv|corp|co)\M', ' ', 'g'), '\s+', ' ', 'g'))
$f$;
CREATE TABLE IF NOT EXISTS crm.investor_directory (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL CHECK (length(name) BETWEEN 2 AND 200), name_key text NOT NULL UNIQUE, verified boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS crm.investor_directory_uses (directory_id uuid NOT NULL REFERENCES crm.investor_directory(id) ON DELETE CASCADE, organization_id uuid NOT NULL REFERENCES core.organizations(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (directory_id, organization_id));
CREATE INDEX IF NOT EXISTS investor_directory_key_trgm ON crm.investor_directory (name_key text_pattern_ops);
GRANT SELECT, INSERT ON crm.investor_directory, crm.investor_directory_uses TO aidi_os_app;
INSERT INTO crm.investor_directory (name, name_key, verified) SELECT n, crm.name_key(n), true FROM (VALUES
  ('Y Combinator'),
  ('Sequoia Capital'),
  ('Andreessen Horowitz'),
  ('Accel'),
  ('Lightspeed Venture Partners'),
  ('Tiger Global'),
  ('Techstars'),
  ('500 Global'),
  ('Antler'),
  ('Seedstars'),
  ('Google for Startups Accelerator'),
  ('TLcom Capital'),
  ('Partech Africa'),
  ('Ventures Platform'),
  ('Future Africa'),
  ('Microtraction'),
  ('LoftyInc Capital'),
  ('Raba Partnership'),
  ('Norrsken22'),
  ('Kepple Africa Ventures'),
  ('Global Ventures'),
  ('4DX Ventures'),
  ('Novastar Ventures'),
  ('Algebra Ventures'),
  ('Sawari Ventures'),
  ('Launch Africa Ventures'),
  ('Golden Palm Investments'),
  ('Ingressive Capital'),
  ('Voltron Capital'),
  ('Oui Capital'),
  ('Saviu Ventures'),
  ('Janngo Capital'),
  ('Quona Capital'),
  ('Accion Venture Lab'),
  ('IFC'),
  ('British International Investment'),
  ('Proparco'),
  ('P1 Ventures'),
  ('Knife Capital'),
  ('Flourish Ventures'),
  ('Almada Ventures'),
  ('The Magna Collective'),
  ('Yango Ventures'),
  ('Uncovered Fund'),
  ('Hashed Emergent'),
  ('Breega'),
  ('Speedinvest'),
  ('Atlantica Ventures'),
  ('Lateral Capital'),
  ('Enza Capital'),
  ('Atlas Capital'),
  ('MaC Venture Capital'),
  ('Visa Foundation'),
  ('Mastercard Foundation'),
  ('Goodwell Investments'),
  ('Lightrock'),
  ('Helios Investment Partners'),
  ('Endeavor Catalyst'),
  ('Kinnevik'),
  ('QED Investors'),
  ('Ribbit Capital'),
  ('Founders Fund'),
  ('General Catalyst'),
  ('Insight Partners'),
  ('SoftBank Vision Fund'),
  ('Tencent'),
  ('Stripe'),
  ('Visa'),
  ('Bitkraft Ventures'),
  ('Plug and Play'),
  ('Jaza Rift Ventures'),
  ('Musha Ventures'),
  ('First Check Africa'),
  ('Aruwa Capital'),
  ('Vested World'),
  ('Unicorn Growth Capital'),
  ('DFS Lab'),
  ('Village Capital'),
  ('Catalyst Fund'),
  ('Zrosk Investment Management'),
  ('Beyond Capital Ventures'),
  ('CRE Venture Capital'),
  ('Chui Ventures'),
  ('Dalberg Catalyst'),
  ('Echo VC'),
  ('FirstCheck Africa'),
  ('Kalon Venture Partners'),
  ('Mobility 54'),
  ('Orange Ventures'),
  ('Sango Capital')) AS s(n) ON CONFLICT (name_key) DO UPDATE SET verified = true;
INSERT INTO crm.investor_directory (name, name_key) SELECT DISTINCT ON (crm.name_key(investor)) investor, crm.name_key(investor) FROM crm.deals WHERE length(crm.name_key(investor)) >= 2 ON CONFLICT (name_key) DO NOTHING;
INSERT INTO crm.investor_directory_uses (directory_id, organization_id) SELECT DISTINCT d2.id, d.organization_id FROM crm.deals d JOIN crm.investor_directory d2 ON d2.name_key = crm.name_key(d.investor) ON CONFLICT DO NOTHING;
ALTER TABLE services.jobs ADD COLUMN IF NOT EXISTS codes text[] NOT NULL DEFAULT '{}';
UPDATE core.plans SET modules = array_append(modules, 'cs_tracker') WHERE code = 'internal' AND NOT ('cs_tracker' = ANY(modules));
COMMIT;
