<script setup lang="ts">
// Financial profile (income, tax, spending, debts, credit scores, goals), documents (drag and drop), the AI review and
// its share link. Used by staff (client page) and by the client (portal).
const props = defineProps<{ api: string; preview?: boolean }>()
const { data, refresh } = await useFetch<Record<string, any>>(() => props.api, { key: 'plan-' + props.api })
const blankP = () => ({ household: { adults: 2, children: 0, location: '' }, incomes: [] as any[], taxes: [] as any[], expenses: [] as any[], debts: [] as any[], credit_scores: [] as any[], goals: [] as any[], notes: '' })
const p = reactive<Record<string, any>>(blankP())
watchEffect(() => { if (data.value) Object.assign(p, blankP(), JSON.parse(JSON.stringify(data.value.profile ?? {}))) })
const sec = ref<'profile' | 'report'>('profile')
const touched = ref(false)
watchEffect(() => { if (data.value?.report && sec.value === 'profile' && !touched.value) sec.value = 'report' })
const cur = ref('USD'); const msg = ref(''); const ok = ref(''); const busy = ref(''); const link = ref(''); const kind = ref('bank_statement')
const add = (k: string, row: Record<string, unknown>) => { touched.value = true; p[k].push(row) }
const err = (e: unknown) => (e as { data?: { data?: { error?: { message?: string } } } }).data?.data?.error?.message ?? 'Could not save.'
const num = (o: any, k: string) => { o[k] = o[k] === '' || o[k] == null ? 0 : Number(o[k]) }
function clean() { for (const k of ['incomes', 'taxes', 'expenses']) for (const r of p[k]) num(r, 'amount'); for (const r of p.debts) { num(r, 'balance'); if (r.rate !== '' && r.rate != null) r.rate = Number(r.rate); else delete r.rate; if (r.payment !== '' && r.payment != null) r.payment = Number(r.payment); else delete r.payment } for (const r of p.credit_scores) num(r, 'score'); for (const r of p.goals) { if (r.target === '' || r.target == null) delete r.target; else r.target = Number(r.target) } p.household.adults = Number(p.household.adults || 0); p.household.children = Number(p.household.children || 0) }
async function save() { if (props.preview) { msg.value = 'Preview only.'; return } busy.value = 'save'; msg.value = ''; ok.value = ''; clean(); try { await $fetch(props.api, { method: 'POST', body: { action: 'save', profile: p } }); ok.value = 'Saved.'; await refresh() } catch (e) { msg.value = err(e) } finally { busy.value = '' } }
async function upload(ev: Event) { if (props.preview) return; const files = Array.from(((ev.target as HTMLInputElement).files ?? []) as File[]); if (!files.length) return; busy.value = 'up'; msg.value = ''; const fd = new FormData(); fd.append('kind', kind.value); for (const f of files) fd.append('file', f); try { const r = await $fetch<{ uploaded: number }>(props.api, { method: 'POST', body: fd }); ok.value = r.uploaded + ' file' + (r.uploaded === 1 ? '' : 's') + ' added.'; await refresh() } catch (e) { msg.value = err(e) } finally { busy.value = '' } }
async function act(action: string, extra: Record<string, unknown> = {}) { if (props.preview) { msg.value = 'Preview only.'; return null } busy.value = action; msg.value = ''; ok.value = ''; try { const r = await $fetch<Record<string, any>>(props.api, { method: 'POST', body: { action, ...extra } }); await refresh(); return r } catch (e) { msg.value = err(e); return null } finally { busy.value = '' } }
async function generate() { await save(); if (msg.value) return; const r = await act('generate'); if (r) { sec.value = 'report'; ok.value = 'Your financial review is ready.' } }
async function share() { const r = await act('share'); if (r?.url) { link.value = r.url; try { await navigator.clipboard.writeText(r.url) } catch { /* ignore */ } } }
const KIND: Record<string, string> = { bank_statement: 'Bank statement', tax_return: 'Tax return', payslip: 'Payslip / salary', credit_report: 'Credit report (FICO, Credit Karma…)', other: 'Other' }
</script>
<template>
  <div v-if="data" class="fp">
    <nav class="s2"><button :class="{ on: sec === 'profile' }" @click="sec = 'profile'; touched = true">Financial details</button><button :class="{ on: sec === 'report' }" :disabled="!data.report" @click="sec = 'report'">Financial review</button></nav>
    <p v-if="msg" class="error">{{ msg }}</p><p v-if="ok" class="okm">{{ ok }}</p>
    <template v-if="sec === 'profile'">
      <div class="card"><h4>Household</h4><div class="g3"><label>Adults<input v-model="p.household.adults" type="number" min="0"></label><label>Children<input v-model="p.household.children" type="number" min="0"></label><label>City / country<input v-model="p.household.location"></label></div><label class="cur">Main currency <select v-model="cur"><option>USD</option><option>NGN</option></select></label></div>
      <div class="card"><div class="h"><h4>Income (salary, business, rent, dividends…)</h4><button class="lk" @click="add('incomes', { who: '', source: '', amount: '', frequency: 'monthly', currency: cur })">+ Add</button></div>
        <div v-for="(r, i) in p.incomes" :key="i" class="row5"><input v-model="r.who" placeholder="Who"><input v-model="r.source" placeholder="Source, e.g. Salary"><input v-model="r.amount" type="number" min="0" placeholder="Amount"><select v-model="r.frequency"><option value="monthly">Monthly</option><option value="annual">Yearly</option></select><select v-model="r.currency"><option>USD</option><option>NGN</option></select><button class="x" @click="p.incomes.splice(i, 1)">×</button></div></div>
      <div class="card"><div class="h"><h4>Tax</h4><button class="lk" @click="add('taxes', { kind: '', amount: '', frequency: 'annual', currency: cur })">+ Add</button></div>
        <div v-for="(r, i) in p.taxes" :key="i" class="row4"><input v-model="r.kind" placeholder="e.g. Federal income tax, PAYE"><input v-model="r.amount" type="number" min="0" placeholder="Amount"><select v-model="r.frequency"><option value="monthly">Monthly</option><option value="annual">Yearly</option></select><select v-model="r.currency"><option>USD</option><option>NGN</option></select><button class="x" @click="p.taxes.splice(i, 1)">×</button></div></div>
      <div class="card"><div class="h"><h4>Spending</h4><button class="lk" @click="add('expenses', { category: '', amount: '', frequency: 'monthly', currency: cur })">+ Add</button></div>
        <div v-for="(r, i) in p.expenses" :key="i" class="row4"><input v-model="r.category" placeholder="Housing, school fees, staff, travel…"><input v-model="r.amount" type="number" min="0" placeholder="Amount"><select v-model="r.frequency"><option value="monthly">Monthly</option><option value="annual">Yearly</option></select><select v-model="r.currency"><option>USD</option><option>NGN</option></select><button class="x" @click="p.expenses.splice(i, 1)">×</button></div></div>
      <div class="card"><div class="h"><h4>Debts (mortgage, loans, cards)</h4><button class="lk" @click="add('debts', { name: '', balance: '', rate: '', payment: '', currency: cur })">+ Add</button></div>
        <div v-for="(r, i) in p.debts" :key="i" class="row5"><input v-model="r.name" placeholder="Name"><input v-model="r.balance" type="number" min="0" placeholder="Balance"><input v-model="r.rate" type="number" min="0" step="0.01" placeholder="Rate %"><input v-model="r.payment" type="number" min="0" placeholder="Monthly payment"><select v-model="r.currency"><option>USD</option><option>NGN</option></select><button class="x" @click="p.debts.splice(i, 1)">×</button></div></div>
      <div class="card"><div class="h"><h4>Credit scores</h4><button class="lk" @click="add('credit_scores', { person: '', score: '', source: 'FICO', date: '' })">+ Add</button></div>
        <div v-for="(r, i) in p.credit_scores" :key="i" class="row4"><input v-model="r.person" placeholder="Person"><input v-model="r.score" type="number" min="300" max="900" placeholder="Score"><select v-model="r.source"><option>FICO</option><option>Credit Karma</option><option>Equifax</option><option>Experian</option><option>TransUnion</option><option>CreditChek</option><option>Other</option></select><input v-model="r.date" type="date"><button class="x" @click="p.credit_scores.splice(i, 1)">×</button></div></div>
      <div class="card"><div class="h"><h4>Goals</h4><button class="lk" @click="add('goals', { name: '', target: '', by: '' })">+ Add</button></div>
        <div v-for="(r, i) in p.goals" :key="i" class="row3"><input v-model="r.name" placeholder="e.g. Children's university, retire at 55, buy a home"><input v-model="r.target" type="number" min="0" placeholder="Target amount"><input v-model="r.by" type="date"><button class="x" @click="p.goals.splice(i, 1)">×</button></div>
        <label class="full">Anything else<textarea v-model="p.notes" rows="2" maxlength="4000" /></label></div>
      <div class="card"><h4>Documents</h4><p class="mut">Bank statements, tax returns, payslips and credit reports. They are kept private and read by AI when preparing the review.</p>
        <div class="dz2"><select v-model="kind"><option v-for="(l, k) in KIND" :key="k" :value="k">{{ l }}</option></select><DropZone multiple accept=".pdf,.png,.jpg,.jpeg,.webp,.csv,.xlsx" :disabled="busy === 'up'" :label="busy === 'up' ? 'Uploading…' : 'Drop files here or click to choose'" hint="PDF, images, CSV or Excel · up to 20 MB each" @change="upload" /></div>
        <div v-for="d in data.docs" :key="d.id" class="rw"><span>{{ KIND[d.kind] ?? d.kind }} · {{ d.name }}</span><button class="lk red" @click="act('remove_doc', { doc_id: d.id })">Remove</button></div></div>
      <div class="acts"><button class="btn secondary" :disabled="!!busy" @click="save">{{ busy === 'save' ? 'Saving…' : 'Save details' }}</button><button class="btn" :disabled="!!busy" @click="generate">{{ busy === 'generate' ? 'Preparing your review… (about a minute)' : data.report ? 'Update financial review' : 'Prepare financial review' }}</button></div>
    </template>
    <template v-else-if="data.report">
      <div class="shr card"><span><b>Share this review</b> with family: they enter their name and email to view, and you are told who looked.</span><span class="sa"><button class="btn sm" :disabled="!!busy" @click="share">{{ data.has_link ? 'Make a new link' : 'Create link' }}</button><button v-if="data.has_link" class="lk red" @click="act('unshare')">Turn off</button></span><span v-if="link" class="mut">Copied: {{ link }}</span></div>
      <FinancialReport :report="data.report.content" :history="data.history" />
      <div v-if="data.views.length" class="card"><h4>Who viewed the shared review</h4><div v-for="(v, i) in data.views" :key="i" class="rw"><span>{{ v.name }} · {{ v.email }}</span><span class="mut">{{ new Date(v.viewed_at).toLocaleString('en-GB') }}</span></div></div>
    </template>
  </div>
</template>
<style scoped>
.fp { display: flex; flex-direction: column; gap: 12px; } .fp *, .fp { box-sizing: border-box; } .s2 { display: flex; gap: 4px; } .s2 button { background: #fff; border: 1px solid var(--c-rule); padding: 7px 14px; font: inherit; font-size: 13.5px; cursor: pointer; } .s2 .on { border-color: var(--c-blue-deep); color: var(--c-blue-deep); font-weight: 600; } .s2 button:disabled { opacity: .45; cursor: default; }
.card h4 { margin: 0; font-size: 14.5px; } .h { display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px; } .mut { color: var(--c-muted); font-size: 12.5px; margin: 4px 0 8px; } .okm { color: var(--c-ok); margin: 0; } .error { color: var(--c-danger); margin: 0; }
input, select, textarea { font: inherit; font-size: 13.5px; padding: 7px 9px; border: 1px solid var(--c-rule-strong); background: #fff; width: 100%; min-width: 0; } label { display: flex; flex-direction: column; gap: 4px; font-size: 12.5px; color: var(--c-muted); } .cur { flex-direction: row; align-items: center; gap: 8px; margin-top: 8px; } .cur select { width: auto; }
.g3 { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 10px; margin-top: 6px; } .row5 { display: grid; grid-template-columns: 1fr 1.4fr 1fr .9fr .7fr 28px; gap: 6px; margin: 4px 0; } .row4 { display: grid; grid-template-columns: 2fr 1fr .9fr .7fr 28px; gap: 6px; margin: 4px 0; } .row3 { display: grid; grid-template-columns: 2.4fr 1fr 1fr 28px; gap: 6px; margin: 4px 0; } .x { background: none; border: 0; color: var(--c-muted); font-size: 18px; cursor: pointer; } .full { margin-top: 8px; }
.dz2 { display: grid; grid-template-columns: 220px minmax(0, 1fr); gap: 10px; align-items: stretch; } .rw { display: flex; justify-content: space-between; gap: 8px; padding: 6px 0; border-top: 1px solid var(--c-rule); font-size: 13px; } .lk { background: none; border: 0; color: var(--c-blue-deep); cursor: pointer; font: inherit; font-size: 12.5px; } .lk.red { color: var(--c-danger); } .acts { display: flex; gap: 8px; }
.shr { display: flex; justify-content: space-between; align-items: center; gap: 10px; flex-wrap: wrap; font-size: 13.5px; } .sa { display: flex; gap: 10px; align-items: center; }
@media (max-width: 900px) { .g3, .row5, .row4, .row3, .dz2 { grid-template-columns: 1fr; } }
</style>
