<script setup lang="ts">
// Investing and savings. Client mode: open the Alpaca account (US) or Fincra wallet (NGN/USD accounts), place their own orders,
// link a bank and move money, buy/sell crypto through Busha (Nigeria), request savings deposits/withdrawals.
// Staff mode: read-only provider view plus the savings desk (open plans, record and confirm deposits).
const props = defineProps<{ api: string; staff?: boolean; clientId?: string }>()
const { data, refresh, error } = await useFetch<Record<string, any>>(() => props.api, { key: 'inv-' + props.api })
const errMsg = computed(() => (error.value as { data?: { data?: { error?: { message?: string } } } } | null)?.data?.data?.error?.message ?? '')
const msg = ref(''); const ok = ref(''); const busy = ref('')
async function act(action: string, body: Record<string, unknown> = {}, url = props.api) { busy.value = action; msg.value = ''; ok.value = ''; try { const r = await $fetch<Record<string, any>>(url, { method: 'POST', body: { action, ...body } }); await refresh(); return r } catch (e) { msg.value = (e as { data?: { data?: { error?: { message?: string } } } }).data?.data?.error?.message ?? 'Something went wrong.'; return null } finally { busy.value = '' } }
const money = (v: number | string | null | undefined, c = 'USD') => (v == null ? '—' : new Intl.NumberFormat('en-US', { style: 'currency', currency: c, maximumFractionDigits: 2 }).format(Number(v)))
// Alpaca
const op = reactive({ given_name: '', family_name: '', date_of_birth: '', tax_id: '', phone: '', street: '', city: '', state: '', postal_code: '', funding_source: 'employment_income', crypto: true, agree: false })
const ord = reactive({ symbol: '', side: 'buy', notional: '' as string | number })
const bk = reactive({ account_owner_name: '', bank_account_type: 'CHECKING', bank_account_number: '', bank_routing_number: '' })
const tr = reactive({ relationship_id: '', amount: '' as string | number, direction: 'INCOMING' })
async function placeOrder() { if (!confirm('Place a market ' + ord.side + ' order for ' + money(Number(ord.notional)) + ' of ' + ord.symbol.toUpperCase() + '? You are making this decision yourself; Aidi does not recommend investments.')) return; const r = await act('alpaca_order', { ...ord, notional: Number(ord.notional) }); if (r) { ok.value = 'Order placed (' + r.order.status + ').'; ord.notional = '' } }
// Fincra
const us = reactive({ first_name: '', last_name: '', birth_date: '', phone: '', nationality: 'NG', occupation: '', employment_status: 'employed', source_of_income: 'salary', income_lower: '', income_upper: '', number: '', street: '', city: '', state: '', zip: '', country: 'NG', doc_number: '', doc_issued: '', doc_expiry: '', tax_country: 'NG', tax_number: '' })
const wd = reactive({ currency: 'NGN', amount: '' as string | number, bank_details: '' })
// Busha
const bu = reactive({ asset: 'BTC', side: 'buy', amount: '' as string | number }); const quote = ref<Record<string, any> | null>(null)
async function getQuote() { const r = await act('busha_quote', { ...bu, amount: Number(bu.amount) }); quote.value = r?.quote ?? null }
async function trade() { if (!confirm('Confirm this crypto ' + bu.side + '? You are making this decision yourself.')) return; const r = await act('busha_trade', { ...bu, amount: Number(bu.amount) }); if (r) { ok.value = 'Done.'; quote.value = null } }
// Savings
const sr = reactive({ plan_id: '', kind: 'deposit', amount: '' as string | number })
const np = reactive({ open: false, name: 'USD savings plan', currency: 'USD', target: '' as string | number, monthly: '' as string | number, matures_on: '' })
const sx = reactive({ plan_id: '', kind: 'deposit', amount: '' as string | number, txn_date: new Date().toISOString().slice(0, 10), note: '' })
</script>
<template>
  <div class="ip">
    <p v-if="errMsg" class="mut">{{ errMsg }}</p>
    <template v-else-if="data">
      <p v-if="msg" class="error">{{ msg }}</p><p v-if="ok" class="okm">{{ ok }}</p>
      <p v-if="!data.enabled.alpaca && !data.enabled.fincra && !data.enabled.busha && !data.savings" class="mut card">{{ staff ? 'No provider is switched on for this client\'s country yet. Turn them on in Wealth → Settings (and add the keys) once licensed.' : 'Investing tools are not available on your account yet.' }}</p>
      <!-- Alpaca (US) -->
      <div v-if="data.enabled.alpaca" class="card"><h3>Investment account <span class="tag">Alpaca · US stocks, ETFs and crypto</span></h3>
        <template v-if="!data.alpaca?.account?.external_id">
          <p class="mut">{{ staff ? 'The client has not opened their account yet.' : 'Open your account. Alpaca checks your identity (it can take a few minutes to a day). Your Social Security number goes straight to Alpaca and is not stored by Aidi.' }}</p>
          <div v-if="!staff" class="g3"><input v-model="op.given_name" placeholder="First name"><input v-model="op.family_name" placeholder="Last name"><input v-model="op.date_of_birth" type="date"><input v-model="op.tax_id" placeholder="Social Security number" autocomplete="off"><input v-model="op.phone" placeholder="Phone (+1…)"><select v-model="op.funding_source"><option value="employment_income">Employment income</option><option value="investments">Investments</option><option value="inheritance">Inheritance</option><option value="business_income">Business income</option><option value="savings">Savings</option><option value="family">Family</option></select>
            <input v-model="op.street" placeholder="Street address"><input v-model="op.city" placeholder="City"><div class="g2i"><input v-model="op.state" maxlength="2" placeholder="State (CA)"><input v-model="op.postal_code" placeholder="ZIP"></div></div>
          <div v-if="!staff" class="cbs"><label><input v-model="op.crypto" type="checkbox"> Also enable crypto</label><label><input v-model="op.agree" type="checkbox"> I accept the Alpaca customer agreement{{ op.crypto ? ' and crypto agreement' : '' }}</label></div>
          <button v-if="!staff" class="btn" :disabled="!!busy || !op.agree" @click="act('alpaca_open', { ...op }).then((r) => r && (ok = 'Submitted. Status: ' + r.status))">{{ busy === 'alpaca_open' ? 'Submitting…' : 'Open account' }}</button></template>
        <template v-else>
          <p class="mut">Status: <b>{{ data.alpaca.status ?? data.alpaca.account.status }}</b>{{ data.alpaca.account.detail?.account_number ? ' · Account ' + data.alpaca.account.detail.account_number : '' }}</p><p v-if="data.alpaca.error" class="error">{{ data.alpaca.error }}</p>
          <div v-if="data.alpaca.trading" class="kp"><div><span>Cash</span><b>{{ money(data.alpaca.trading.cash) }}</b></div><div><span>Portfolio value</span><b>{{ money(data.alpaca.trading.equity) }}</b></div><div><span>Buying power</span><b>{{ money(data.alpaca.trading.buying_power) }}</b></div></div>
          <table v-if="data.alpaca.positions?.length" class="table"><thead><tr><th>Holding</th><th class="n">Units</th><th class="n">Value</th><th class="n">Gain</th></tr></thead><tbody><tr v-for="p in data.alpaca.positions" :key="p.symbol"><td><b>{{ p.symbol }}</b><span class="s">{{ p.asset_class === 'crypto' ? 'Crypto' : 'Stock / ETF' }}</span></td><td class="n">{{ Number(p.qty).toLocaleString('en-US', { maximumFractionDigits: 6 }) }}</td><td class="n">{{ money(p.market_value) }}</td><td class="n" :class="Number(p.unrealized_pl) >= 0 ? 'up' : 'dn'">{{ money(p.unrealized_pl) }}</td></tr></tbody></table>
          <div v-if="!staff" class="sub2"><h4>Buy or sell</h4><div class="row"><input v-model="ord.symbol" placeholder="Symbol: VOO, AAPL, BTC/USD" class="w1"><select v-model="ord.side"><option value="buy">Buy</option><option value="sell">Sell</option></select><input v-model="ord.notional" type="number" min="1" placeholder="Amount (USD)"><button class="btn sm" :disabled="!!busy || !ord.symbol || !ord.notional" @click="placeOrder">Place order</button></div><p class="mut">Market orders. You choose what to buy and sell; Aidi provides the tool and does not give recommendations.</p></div>
          <div v-if="data.alpaca.orders?.length" class="sub2"><h4>Recent orders</h4><div v-for="o in data.alpaca.orders.slice(0, 8)" :key="o.id" class="rw"><span>{{ o.side }} {{ o.symbol }} · {{ o.notional ? money(o.notional) : o.qty + ' units' }}</span><span class="mut">{{ o.status }} · {{ new Date(o.created_at).toLocaleDateString('en-GB') }}</span></div></div>
          <div class="sub2"><h4>Move money</h4><div v-for="b in data.alpaca.banks ?? []" :key="b.id" class="rw"><span>{{ b.bank_account_type }} •••{{ String(b.bank_account_number ?? '').slice(-4) }} · {{ b.account_owner_name }}</span><span class="mut">{{ b.status }}</span></div>
            <template v-if="!staff"><div v-if="!(data.alpaca.banks ?? []).length" class="row"><input v-model="bk.account_owner_name" placeholder="Account holder"><select v-model="bk.bank_account_type"><option>CHECKING</option><option>SAVINGS</option></select><input v-model="bk.bank_account_number" placeholder="Account number"><input v-model="bk.bank_routing_number" placeholder="Routing number"><button class="btn sm secondary" :disabled="!!busy" @click="act('alpaca_bank', { ...bk })">Link bank</button></div>
              <div v-else class="row"><select v-model="tr.relationship_id"><option value="">Choose bank</option><option v-for="b in data.alpaca.banks" :key="b.id" :value="b.id">•••{{ String(b.bank_account_number ?? '').slice(-4) }}</option></select><select v-model="tr.direction"><option value="INCOMING">Add money</option><option value="OUTGOING">Withdraw</option></select><input v-model="tr.amount" type="number" min="1" placeholder="Amount (USD)"><button class="btn sm" :disabled="!!busy || !tr.relationship_id || !tr.amount" @click="act('alpaca_transfer', { ...tr, amount: Number(tr.amount) }).then((r) => r && (ok = 'Transfer ' + r.transfer.status))">Transfer</button></div></template>
            <div v-for="t in data.alpaca.transfers ?? []" :key="t.id" class="rw"><span>{{ t.direction === 'INCOMING' ? 'In' : 'Out' }} · {{ money(t.amount) }}</span><span class="mut">{{ t.status }} · {{ new Date(t.created_at).toLocaleDateString('en-GB') }}</span></div></div>
        </template></div>
      <div v-else-if="data.switched?.alpaca && staff" class="card mut">Alpaca is switched on for the US but its keys are not set (NUXT_ALPACA_CLIENT_ID, NUXT_ALPACA_CLIENT_SECRET, NUXT_ALPACA_BASE_URL).</div>
      <!-- Fincra wallet -->
      <div v-if="data.enabled.fincra && data.fincra" class="card"><h3>Wallet <span class="tag">Fincra · {{ data.fincra.currencies.join(' and ') }} accounts</span></h3>
        <div class="kp"><div v-for="c in data.fincra.currencies" :key="c"><span>{{ c }} balance</span><b>{{ money(data.fincra.balances[c]?.balance ?? 0, c) }}</b><em v-if="data.fincra.balances[c]?.pending" class="s">{{ money(data.fincra.balances[c].pending, c) }} withdrawal pending</em></div></div>
        <div v-for="c in data.fincra.currencies" :key="'va' + c" class="sub2"><h4>{{ c }} account</h4>
          <template v-for="va in data.fincra.accounts.filter((x: any) => x.currency === c)" :key="va.currency">
            <p v-if="va.account?.accountNumber" class="acct">Add money by transfer to <b>{{ va.account.accountNumber }}</b> · {{ va.account.bankName }}{{ va.account.accountName ? ' · ' + va.account.accountName : '' }}<template v-if="va.account.otherInfo?.addressableIn"> · {{ va.account.otherInfo.addressableIn }}{{ va.account.otherInfo.memo ? ' · memo ' + va.account.otherInfo.memo : '' }}</template><template v-if="va.account.bankCode"> · routing {{ va.account.bankCode }}</template></p>
            <p v-else class="mut">Status: <b>{{ va.status }}</b>{{ va.reason ? ' · ' + va.reason : va.status === 'pending' || va.status === 'approved' ? ' · Fincra is reviewing the request; the account number appears here once issued.' : '' }}</p></template>
          <template v-if="!staff && !data.fincra.accounts.some((x: any) => x.currency === c && x.status !== 'declined')">
            <template v-if="c === 'NGN'"><p class="mut">Get your own Naira account number for adding money. Uses your verified BVN.</p><button class="btn sm" :disabled="!!busy" @click="act('fincra_ngn')">{{ busy === 'fincra_ngn' ? 'Opening…' : 'Open Naira account' }}</button></template>
            <template v-else><p class="mut">A USD account in your name (ACH, wire, SWIFT; up to $10,000 a month). First upload your passport and a proof of address from the last 3 months under Financial plan → Documents.</p>
              <div class="g3"><input v-model="us.first_name" placeholder="First name (as on passport)"><input v-model="us.last_name" placeholder="Last name"><input v-model="us.birth_date" type="date"><input v-model="us.phone" placeholder="Phone"><input v-model="us.nationality" maxlength="2" placeholder="Nationality (NG, US…)"><input v-model="us.occupation" placeholder="Occupation">
                <select v-model="us.employment_status"><option value="employed">Employed</option><option value="self_employed">Self-employed</option><option value="retired">Retired</option><option value="freelancer">Freelancer</option><option value="other">Other</option></select><select v-model="us.source_of_income"><option value="salary">Salary</option><option value="business_income">Business income</option><option value="investment">Investments</option><option value="inheritance">Inheritance</option><option value="pension">Pension</option><option value="other">Other</option></select><div class="g2i"><input v-model="us.income_lower" placeholder="Income from"><input v-model="us.income_upper" placeholder="Income to"></div>
                <input v-model="us.number" placeholder="House number"><input v-model="us.street" placeholder="Street"><input v-model="us.city" placeholder="City"><input v-model="us.state" placeholder="State"><input v-model="us.zip" placeholder="Postal / ZIP code"><input v-model="us.country" maxlength="2" placeholder="Country (NG, US…)">
                <input v-model="us.doc_number" placeholder="Passport number"><input v-model="us.doc_issued" type="date" title="Passport issue date"><input v-model="us.doc_expiry" type="date" title="Passport expiry date"><input v-model="us.tax_country" maxlength="2" placeholder="Tax country (NG, US)"><input v-if="us.tax_country.toUpperCase() === 'US'" v-model="us.tax_number" placeholder="US tax number (SSN)"></div>
              <button class="btn sm" :disabled="!!busy" @click="act('fincra_usd', { ...us }).then((r) => r && (ok = 'USD account requested. Fincra usually reviews within a few days.'))">{{ busy === 'fincra_usd' ? 'Sending…' : 'Request USD account' }}</button></template></template></div>
        <div class="sub2"><h4>Activity</h4><div v-for="t in data.fincra.txns" :key="t.id" class="rw"><span>{{ t.kind }} · {{ money(t.amount, t.currency) }}{{ t.detail?.sender ? ' · from ' + t.detail.sender : '' }}{{ t.detail?.bank_details ? ' · to ' + t.detail.bank_details : '' }}</span><span><span class="st" :class="t.status">{{ t.status }}</span> <span class="mut">{{ new Date(t.created_at).toLocaleDateString('en-GB') }}</span><template v-if="staff && t.status === 'requested'"> <button class="lk" @click="act('confirm', { txn_id: t.id }, '/api/wm/wallet')">Paid out</button> <button class="lk red" @click="act('reject', { txn_id: t.id }, '/api/wm/wallet')">Reject</button></template></span></div><p v-if="!data.fincra.txns.length" class="mut">No activity yet.</p>
          <div v-if="!staff" class="row"><select v-model="wd.currency"><option v-for="c in data.fincra.currencies" :key="c">{{ c }}</option></select><input v-model="wd.amount" type="number" min="1" placeholder="Amount"><input v-model="wd.bank_details" class="w1" placeholder="Pay into: bank, account number, account name"><button class="btn sm secondary" :disabled="!!busy || !wd.amount || !wd.bank_details" @click="act('fincra_withdraw', { ...wd, amount: Number(wd.amount) }).then((r) => r && (ok = 'Withdrawal requested. We will confirm once it is paid.'))">Withdraw</button></div></div></div>
      <div v-else-if="data.switched?.fincra && staff" class="card mut">Fincra is switched on but its keys are not set (NUXT_FINCRA_API_KEY, NUXT_FINCRA_BASE_URL, NUXT_FINCRA_WEBHOOK_SECRET).</div>
      <!-- Busha (Nigeria) -->
      <div v-if="data.enabled.busha" class="card"><h3>Crypto <span class="tag">Busha</span></h3>
        <template v-if="!staff"><div class="row"><select v-model="bu.asset"><option>BTC</option><option>ETH</option><option>USDT</option><option>USDC</option><option>SOL</option></select><select v-model="bu.side"><option value="buy">Buy with Naira</option><option value="sell">Sell for Naira</option></select><input v-model="bu.amount" type="number" min="1" :placeholder="bu.side === 'buy' ? 'Amount (NGN)' : 'Amount (' + bu.asset + ')'"><button class="btn sm secondary" :disabled="!!busy || !bu.amount" @click="getQuote">Get quote</button></div>
          <div v-if="quote" class="qt"><span>You {{ bu.side === 'buy' ? 'get' : 'receive' }} about <b>{{ quote.target_amount }} {{ bu.side === 'buy' ? bu.asset : 'NGN' }}</b>{{ quote.rate ? ' at ' + quote.rate : '' }}</span><button class="btn sm" :disabled="!!busy" @click="trade">Confirm</button></div></template>
        <p class="mut">Purchases are recorded in your holdings. Aidi does not recommend coins or timing.</p></div>
      <!-- Savings -->
      <div v-if="data.savings" class="card"><h3>Savings plans</h3>
        <div v-for="p in data.savings" :key="p.id" class="sp"><div class="sph"><span><b>{{ p.name }}</b><span class="s">{{ p.rate }}% a year · {{ p.provider === 'manual' ? p.vendor ?? 'Partner' : p.provider }} · since {{ p.started_on }}{{ p.matures_on ? ' · matures ' + p.matures_on : '' }}</span></span><span class="spb"><b>{{ money(p.balance, p.currency) }}</b><span class="s">{{ money(p.interest, p.currency) }} interest earned</span></span></div>
          <div v-if="p.target" class="bar"><i :style="{ width: Math.min(100, (p.balance / p.target) * 100) + '%' }" /></div>
          <div v-for="t in p.txns.slice(0, 6)" :key="t.id" class="rw"><span>{{ t.kind }} · {{ money(t.amount, p.currency) }} · {{ t.txn_date }}</span><span><span class="st" :class="t.status">{{ t.status }}</span><template v-if="staff && t.status === 'requested'"> <button class="lk" @click="act('confirm', { txn_id: t.id }, '/api/wm/savings')">Confirm</button> <button class="lk red" @click="act('reject', { txn_id: t.id }, '/api/wm/savings')">Reject</button></template></span></div>
          <a v-if="p.certificate_doc_id" :href="'/api/wm/doc/' + p.certificate_doc_id" target="_blank" class="lk">Certificate</a></div>
        <p v-if="!data.savings.length" class="mut">{{ staff ? 'No plans yet.' : 'You have no savings plans yet. Ask your Aidi Wealth contact to open one.' }}</p>
        <div v-if="!staff && data.savings.length" class="row"><select v-model="sr.plan_id"><option value="">Choose plan</option><option v-for="p in data.savings" :key="p.id" :value="p.id">{{ p.name }}</option></select><select v-model="sr.kind"><option value="deposit">Add money</option><option value="withdrawal">Withdraw</option></select><input v-model="sr.amount" type="number" min="1" placeholder="Amount"><button class="btn sm" :disabled="!!busy || !sr.plan_id || !sr.amount" @click="act('savings_request', { ...sr, amount: Number(sr.amount) }).then((r) => r && (ok = 'Request sent. We will confirm once the money moves.'))">Request</button></div>
        <template v-if="staff"><div class="row"><select v-model="sx.plan_id"><option value="">Record for plan…</option><option v-for="p in data.savings" :key="p.id" :value="p.id">{{ p.name }}</option></select><select v-model="sx.kind"><option value="deposit">Deposit</option><option value="withdrawal">Withdrawal</option></select><input v-model="sx.amount" type="number" min="0" placeholder="Amount"><input v-model="sx.txn_date" type="date"><button class="btn sm secondary" :disabled="!sx.plan_id || !sx.amount" @click="act('txn', { ...sx, amount: Number(sx.amount) }, '/api/wm/savings')">Record</button></div>
          <button class="lk" @click="np.open = !np.open">{{ np.open ? 'Close' : '+ Open a savings plan' }}</button>
          <div v-if="np.open" class="row"><input v-model="np.name" placeholder="Plan name"><select v-model="np.currency"><option>USD</option><option>NGN</option></select><input v-model="np.target" type="number" min="0" placeholder="Target"><input v-model="np.monthly" type="number" min="0" placeholder="Monthly"><input v-model="np.matures_on" type="date"><button class="btn sm" @click="act('create', { client_id: clientId, name: np.name, currency: np.currency, target: np.target === '' ? null : Number(np.target), monthly: np.monthly === '' ? null : Number(np.monthly), matures_on: np.matures_on || undefined }, '/api/wm/savings').then((r) => r && (np.open = false))">Open plan</button></div></template></div>
    </template>
  </div>
</template>
<style scoped>
.ip { display: flex; flex-direction: column; gap: 12px; } .ip * { box-sizing: border-box; } h3 { margin: 0 0 8px; font-size: 15px; display: flex; align-items: center; gap: 8px; flex-wrap: wrap; } h4 { margin: 0 0 6px; font-size: 13.5px; } .tag { font-size: 11.5px; font-weight: 500; background: var(--c-paper-2); padding: 2px 8px; color: var(--c-ink-soft); }
.mut { color: var(--c-muted); font-size: 12.5px; margin: 4px 0; } .okm { color: var(--c-ok); margin: 0; } .error { color: var(--c-danger); margin: 0; font-size: 13px; } .s { display: block; font-size: 12px; color: var(--c-muted); }
input, select { font: inherit; font-size: 13.5px; padding: 7px 9px; border: 1px solid var(--c-rule-strong); background: #fff; min-width: 0; } .g3 { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 8px; margin: 8px 0; } .g2i { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; } .row { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; margin: 8px 0; } .row input { flex: 1; min-width: 120px; } .w1 { flex: 2 !important; }
.cbs { display: flex; flex-direction: column; gap: 4px; font-size: 13px; margin: 6px 0 10px; } .cbs input { width: auto; margin-right: 6px; } .kp { display: flex; gap: 28px; margin: 8px 0; flex-wrap: wrap; } .kp span { display: block; font-size: 12px; color: var(--c-muted); } .kp b { font-size: 20px; }
.table { width: 100%; border-collapse: collapse; font-size: 13px; margin: 6px 0; } .table th { text-align: left; padding: 6px 8px; font-weight: 500; color: var(--c-muted); } .table td { padding: 8px; border-top: 1px solid var(--c-rule); } .n { text-align: right; } .up { color: var(--c-ok); } .dn { color: var(--c-danger); }
.sub2 { border-top: 1px solid var(--c-rule); margin-top: 10px; padding-top: 10px; } .rw { display: flex; justify-content: space-between; gap: 8px; padding: 5px 0; font-size: 13px; border-top: 1px solid var(--c-rule); } .acct { font-size: 14px; background: var(--c-signal-soft); padding: 10px 12px; margin: 8px 0 0; }
.qt { display: flex; justify-content: space-between; align-items: center; gap: 8px; background: var(--c-paper-2); padding: 8px 12px; font-size: 13.5px; } .sp { border-top: 1px solid var(--c-rule); padding: 10px 0; } .sph { display: flex; justify-content: space-between; gap: 10px; } .spb { text-align: right; } .spb b { font-size: 18px; }
.bar { height: 6px; background: var(--c-paper-2); margin: 6px 0; } .bar i { display: block; height: 100%; background: var(--c-ok); } .st { font-size: 11.5px; padding: 1px 7px; background: var(--c-paper-2); } .st.requested { background: rgba(181,71,8,.09); color: var(--c-warn); } .st.rejected { color: var(--c-danger); }
.lk { background: none; border: 0; color: var(--c-blue-deep); cursor: pointer; font: inherit; font-size: 12.5px; padding: 0; text-decoration: none; } .lk.red { color: var(--c-danger); }
@media (max-width: 800px) { .g3 { grid-template-columns: 1fr; } }
</style>
