<script setup lang="ts">
// One wealth client: summary, holdings, accounts, household (family view link), KYC, advisers and fees.
const id = useRoute().params.id as string
const { data, refresh } = await useFetch<Record<string, any>>('/api/wm/clients/' + id)
useHead({ title: () => (data.value?.client?.name ?? 'Wealth client') })
const tab = ref('summary')
const TABS: [string, string][] = [['summary', 'Summary'], ['holdings', 'Holdings'], ['accounts', 'Accounts'], ['household', 'Household'], ['kyc', 'KYC'], ['fees', 'Advisers & fees']]
const MODEL: Record<string, string> = { managed: 'Managed', advisor: 'Adviser-connected', self_directed: 'Self-directed' }
const money = (v: number | string | null, c: string) => (v == null ? '—' : new Intl.NumberFormat('en-US', { style: 'currency', currency: c, maximumFractionDigits: 0 }).format(Number(v)))
const msg = ref(''); const ok = ref('')
async function act(action: string, extra: Record<string, unknown> = {}) { msg.value = ''; ok.value = ''; try { const r = await $fetch<Record<string, any>>('/api/wm/clients/' + id, { method: 'POST', body: { action, ...extra } }); await refresh(); return r } catch (e) { msg.value = (e as { data?: { data?: { error?: { message?: string } } } }).data?.data?.error?.message ?? 'Could not save.' } }
const ed = reactive<Record<string, any>>({}); watchEffect(() => { if (data.value) Object.assign(ed, { name: data.value.client.name, kind: data.value.client.kind, model: data.value.client.model, status: data.value.client.status, tag: data.value.client.tag ?? '', contact_name: data.value.client.contact_name ?? '', email: data.value.client.email ?? '', phone: data.value.client.phone ?? '', risk_profile: data.value.client.risk_profile ?? '', notes: data.value.client.notes ?? '' }) })
const hf = reactive({ open: false, edit: null as Record<string, any> | null })
const ac = reactive({ open: false, account_id: '', institution: '', kind: 'brokerage', name: '', currency: 'USD', balance: '' as string | number, cash_part: '' as string | number, as_of: new Date().toISOString().slice(0, 10), managed_by: '' })
function editAcc(a?: Record<string, any>) { Object.assign(ac, { open: true, account_id: '', institution: '', kind: 'brokerage', name: '', currency: 'USD', balance: '', cash_part: '', as_of: new Date().toISOString().slice(0, 10), managed_by: '' }, a ? { ...a, account_id: a.id, name: a.name ?? '', cash_part: a.cash_part ?? '', managed_by: a.managed_by ?? '' } : {}) }
async function saveAcc() { await act('account', { ...ac }); ac.open = false }
const mb = reactive({ name: '', relationship: '', email: '' }); const link = ref('')
async function newLink() { const r = await act('view_link'); if (r?.url) { link.value = r.url; try { await navigator.clipboard.writeText(r.url) } catch { /* ignore */ } } }
const kyc = reactive({ bvn: '', nin: '' }); const kfile = ref<File | null>(null)
async function bvn() { const r = await act('kyc_bvn', { ...kyc }); if (r) ok.value = r.verified ? 'BVN verified with Prembly.' : 'Prembly could not verify: ' + r.detail }
async function kycDoc() { if (!kfile.value) return; const fd = new FormData(); fd.append('file', kfile.value); try { await $fetch('/api/wm/clients/' + id + '/kyc-doc', { method: 'POST', body: fd }); await refresh(); ok.value = 'Document saved. Review it, then mark KYC verified.' } catch (e) { msg.value = (e as { data?: { data?: { error?: { message?: string } } } }).data?.data?.error?.message ?? 'Could not upload.' } }
const lf = reactive({ firm_id: '', adviser_name: '', started_on: '' })
async function delClient() { if (!confirm('Delete this wealth client? Their holdings stay in Investments & AUM, unlinked.')) return; await act('delete'); if (!msg.value) await navigateTo('/wealth-mgmt?t=clients') }
const fee = reactive({ kind: 'subscription', period: '', amount: '' as string | number, note: '' })
const { data: firms } = await useFetch<{ firms: { id: string; name: string }[] }>('/api/wm/overview', { key: 'wm-firms', transform: (d: any) => ({ firms: d.firms }) })
</script>
<template>
  <section v-if="data">
    <NuxtLink to="/wealth-mgmt?t=clients" class="back">← Wealth clients</NuxtLink>
    <div class="hd"><div><p class="label">{{ data.client.country === 'US' ? 'United States' : 'Nigeria' }} · {{ data.client.entity }} · {{ MODEL[data.client.model] }}</p><h1>{{ data.client.name }}</h1><p class="mut">{{ data.client.contact_name }}{{ data.client.email ? ' · ' + data.client.email : '' }} · status {{ data.client.status }} · KYC {{ data.client.kyc_status.replace('_', ' ') }}</p></div>
      <div class="acts"><button class="btn secondary" @click="act('invite').then(() => ok = 'Portal invitation sent.')">{{ data.client.user_id ? 'Resend portal invite' : 'Invite to portal' }}</button><NuxtLink class="btn secondary" :to="'/w?client=' + id">Preview portal</NuxtLink></div></div>
    <p v-if="msg" class="error">{{ msg }}</p><p v-if="ok" class="okm">{{ ok }}</p>
    <nav class="sub"><button v-for="[k, l] in TABS" :key="k" :class="{ on: tab === k }" @click="tab = k">{{ l }}</button></nav>
    <template v-if="tab === 'summary'"><WealthSummary :s="data.summary" /><p v-if="data.advisory_estimate != null" class="mut">Advisory fee at the current schedule: about {{ money(data.advisory_estimate, 'USD') }} a year.</p>
      <div class="card fm2"><h3>Details</h3><div class="g3"><label>Name<input v-model="ed.name"></label><label>Type<select v-model="ed.kind"><option value="individual">Individual</option><option value="family">Family</option><option value="business">Business</option></select></label><label>Tag<input v-model="ed.tag"></label>
          <label>Service<select v-model="ed.model"><option value="advisor">Adviser-connected</option><option value="self_directed">Self-directed</option><option value="managed">Managed</option></select></label><label>Status<select v-model="ed.status"><option>prospect</option><option>onboarding</option><option>active</option><option>paused</option><option>closed</option></select></label><label>Risk profile<input v-model="ed.risk_profile" placeholder="e.g. Balanced"></label>
          <label>Main contact<input v-model="ed.contact_name"></label><label>Email<input v-model="ed.email"></label><label>Phone<input v-model="ed.phone"></label></div><label>Notes<textarea v-model="ed.notes" rows="2" /></label><div class="row"><button class="btn" @click="act('update', ed)">Save details</button><button class="lk red" @click="delClient">Delete client</button></div></div></template>
    <template v-else-if="tab === 'holdings'"><div class="card tc"><div class="ch"><h3>Holdings</h3><button class="btn secondary sm" @click="hf.open = true; hf.edit = null">Add holding</button></div>
      <table v-if="data.summary.holdings.length" class="table"><thead><tr><th>Holding</th><th>Type</th><th>Where</th><th class="n">Cost</th><th class="n">Value</th><th /></tr></thead><tbody><tr v-for="h in data.summary.holdings" :key="h.id"><td><b>{{ h.name }}</b><span class="s">{{ h.meta?.symbol ?? '' }}{{ h.meta?.ounces ? h.meta.ounces + ' oz' : '' }}{{ h.meta?.rate ? h.meta.rate + '% a year' : '' }} · as of {{ h.as_of }}</span></td><td>{{ h.category.replace('_', ' ') }}</td><td>{{ h.platform ?? '—' }}</td><td class="n">{{ money(h.cost, h.currency) }}</td><td class="n"><b>{{ money(h.current_value, h.currency) }}</b></td><td><button class="lk" @click="hf.open = true; hf.edit = { ...h, cost: h.cost != null ? Number(h.cost) : '', current_value: h.current_value != null ? Number(h.current_value) : '' }">Edit</button></td></tr></tbody></table><p v-else class="mut pad">No holdings yet.</p></div>
      <AppModal :open="hf.open" :title="hf.edit ? 'Edit holding' : 'Add a holding'" wide @close="hf.open = false"><HoldingForm :key="hf.edit?.id ?? 'new'" :client-id="id" :edit="hf.edit" @saved="hf.open = false; refresh()" @close="hf.open = false" /></AppModal></template>
    <template v-else-if="tab === 'accounts'"><div class="card tc"><div class="ch"><h3>Accounts on other platforms</h3><button class="btn secondary sm" @click="editAcc()">Add account</button></div>
      <table v-if="data.summary.accounts.length" class="table"><thead><tr><th>Institution</th><th>Type</th><th>Managed by</th><th class="n">Balance</th><th>As of</th><th /></tr></thead><tbody><tr v-for="a in data.summary.accounts" :key="a.id"><td><b>{{ a.institution }}</b><span class="s">{{ a.name }}</span></td><td>{{ a.kind }}</td><td>{{ a.managed_by ?? '—' }}</td><td class="n">{{ money(a.balance, a.currency) }}</td><td>{{ a.as_of }}</td><td><button class="lk" @click="editAcc(a)">Edit</button></td></tr></tbody></table><p v-else class="mut pad">Brokerage, crypto, savings and bank accounts the client holds elsewhere (Robinhood, Busha, Cowrywise, their bank…).</p></div>
      <div v-if="data.summary.banks.length" class="card"><h3>Linked banks (Plaid)</h3><div v-for="b in data.summary.banks" :key="b.id" class="rw"><span>{{ b.institution }} · {{ b.name }}{{ b.mask ? ' ••' + b.mask : '' }}</span><b>{{ money(b.current, b.currency) }}</b></div></div>
      <AppModal :open="ac.open" :title="ac.account_id ? 'Edit account' : 'Add an account'" wide @close="ac.open = false"><div class="fm"><div class="g3"><label>Institution<input v-model="ac.institution" placeholder="Robinhood, Busha, Cowrywise…"></label><label>Type<select v-model="ac.kind"><option value="brokerage">Brokerage</option><option value="crypto">Crypto</option><option value="savings">Savings</option><option value="bank">Bank</option><option value="retirement">Retirement</option><option value="other">Other</option></select></label><label>Account name<input v-model="ac.name"></label>
          <label>Currency<select v-model="ac.currency"><option>USD</option><option>NGN</option></select></label><label>Balance<input v-model="ac.balance" type="number" min="0"></label><label>As of<input v-model="ac.as_of" type="date"></label><label>Managed by (adviser)<input v-model="ac.managed_by"></label></div></div>
        <template #foot><button v-if="ac.account_id" class="btn secondary danger" @click="act('account', { account_id: ac.account_id, delete: true }).then(() => ac.open = false)">Remove</button><button class="btn secondary" @click="ac.open = false">Cancel</button><button class="btn" :disabled="!ac.institution" @click="saveAcc">Save</button></template></AppModal></template>
    <template v-else-if="tab === 'household'"><div class="card"><h3>Family members</h3><p class="mut">Family members don't get a login. They view the household through a link, giving their name and email; the client is emailed each time.</p>
        <div v-for="m in data.members" :key="m.id" class="rw"><span><b>{{ m.name }}</b> {{ m.relationship ? '· ' + m.relationship : '' }} {{ m.email ? '· ' + m.email : '' }}</span><button class="lk red" @click="act('remove_member', { member_id: m.id })">Remove</button></div>
        <div class="g3 add"><input v-model="mb.name" placeholder="Name"><input v-model="mb.relationship" placeholder="Relationship"><input v-model="mb.email" placeholder="Email"></div><button class="btn secondary sm" :disabled="!mb.name" @click="act('add_member', { ...mb }).then(() => Object.assign(mb, { name: '', relationship: '', email: '' }))">Add member</button>
        <div class="lnk"><button class="btn sm" @click="newLink">{{ data.has_link ? 'Make a new family link' : 'Create family link' }}</button><button v-if="data.has_link" class="lk red" @click="act('revoke_link')">Turn off link</button><span v-if="link" class="mut">Copied: {{ link }}</span></div></div>
      <div class="card"><h3>Who viewed</h3><div v-for="(v, i) in data.views" :key="i" class="rw"><span>{{ v.name }} · {{ v.email }}</span><em>{{ new Date(v.viewed_at).toLocaleString('en-GB') }}</em></div><p v-if="!data.views.length" class="mut">No views yet.</p></div></template>
    <template v-else-if="tab === 'kyc'"><div class="card"><h3>Identity checks</h3>
        <template v-if="data.client.country === 'NG'"><p class="mut">Nigeria: BVN through Prembly.{{ data.client.bvn_last4 ? ' BVN on file •••' + data.client.bvn_last4 + '.' : '' }}{{ data.client.kyc_detail?.name ? ' Name on BVN: ' + data.client.kyc_detail.name + '.' : '' }}</p><div class="g3 add"><input v-model="kyc.bvn" inputmode="numeric" maxlength="11" placeholder="BVN (11 digits)"><input v-model="kyc.nin" inputmode="numeric" maxlength="11" placeholder="NIN (optional)"><button class="btn sm" :disabled="kyc.bvn.length !== 11" @click="bvn">Verify with Prembly</button></div></template>
        <template v-else><p class="mut">United States: upload a government ID (and proof of address), review it, then mark KYC verified. When Alpaca is switched on, account opening runs Alpaca's own identity check.</p><div class="row"><input type="file" accept=".pdf,image/png,image/jpeg,image/webp" @change="kfile = ($event.target as HTMLInputElement).files?.[0] ?? null"><button class="btn sm" :disabled="!kfile" @click="kycDoc">Upload</button></div></template>
        <div class="row"><span>Status: <b>{{ data.client.kyc_status.replace('_', ' ') }}</b></span><button class="lk" @click="act('kyc_status', { status: 'verified', provider: 'manual' })">Mark verified</button><button class="lk red" @click="act('kyc_status', { status: 'failed' })">Mark failed</button></div></div></template>
    <template v-else-if="tab === 'fees'"><div class="card"><h3>Advisers</h3><div v-for="f in data.firms" :key="f.id" class="rw"><span><b>{{ f.name }}</b>{{ f.adviser_name ? ' · ' + f.adviser_name : '' }} · {{ f.terms_type === 'percent_of_fee' ? f.terms_rate + '% of their fee' : money(f.terms_amount, f.terms_currency) + ' flat' }}</span><button class="lk red" @click="act('link_firm', { link_id: f.id, delete: true })">Remove</button></div>
        <div class="g3 add"><select v-model="lf.firm_id"><option value="">Choose a firm</option><option v-for="x in firms?.firms ?? []" :key="x.id" :value="x.id">{{ x.name }}</option></select><input v-model="lf.adviser_name" placeholder="Adviser at the firm"><input v-model="lf.started_on" type="date"></div><button class="btn secondary sm" :disabled="!lf.firm_id" @click="act('link_firm', { ...lf })">Link adviser</button></div>
      <div class="card"><h3>Fees</h3><div v-for="f in data.fees" :key="f.id" class="rw"><span>{{ f.kind }}{{ f.period ? ' · ' + f.period : '' }} · {{ money(f.amount, f.currency) }}</span><span><span class="st" :class="f.status">{{ f.status }}</span> <button v-if="f.status !== 'paid'" class="lk" @click="act('fee', { fee_id: f.id, status: 'paid' })">Mark paid</button></span></div>
        <div class="g3 add"><select v-model="fee.kind"><option value="subscription">Subscription</option><option value="advisory">Advisory</option><option value="referral">Referral</option></select><input v-model="fee.period" placeholder="Period, e.g. Oct 2026"><input v-model="fee.amount" type="number" min="0" placeholder="Amount"></div><button class="btn secondary sm" :disabled="fee.amount === ''" @click="act('fee', { ...fee })">Add fee</button>
        <p class="mut">Paid fees post to the books of {{ data.client.entity }}. Subscription: {{ money(data.settings[data.client.country].subscription, data.settings[data.client.country].currency) }}/month.</p></div></template>
  </section>
</template>
<style scoped>
.back { color: var(--c-muted); text-decoration: none; font-size: 13.5px; } .hd { display: flex; justify-content: space-between; align-items: flex-end; gap: 12px; flex-wrap: wrap; } .hd h1 { margin: 2px 0; } .acts { display: flex; gap: 8px; } .mut { color: var(--c-muted); font-size: 13px; } .okm { color: var(--c-ok); } .error { color: var(--c-danger); }
.sub { display: flex; gap: 4px; background: var(--c-paper-2); padding: 4px; margin: 14px 0; width: fit-content; max-width: 100%; overflow-x: auto; } .sub button { background: none; border: 0; padding: 8px 14px; font: inherit; font-size: 14px; cursor: pointer; white-space: nowrap; } .sub .on { background: #fff; font-weight: 600; box-shadow: 0 1px 3px rgba(12,26,46,.08); }
.card { margin-bottom: 12px; } .card h3 { margin: 0 0 8px; font-size: 15px; } .tc { padding: 0; overflow-x: auto; } .ch { display: flex; justify-content: space-between; align-items: center; padding: 12px 14px; } .table { width: 100%; border-collapse: collapse; font-size: 13.5px; } .table th { text-align: left; padding: 10px 14px; } .table td { padding: 11px 14px; border-bottom: 1px solid var(--c-rule); vertical-align: top; } .n { text-align: right; white-space: nowrap; } .s { display: block; font-size: 12.5px; color: var(--c-muted); } .pad { padding: 14px; margin: 0; }
.rw { display: flex; justify-content: space-between; gap: 10px; padding: 7px 0; border-top: 1px solid var(--c-rule); font-size: 13.5px; } .rw em { font-style: normal; color: var(--c-muted); font-size: 12.5px; } .lk { background: none; border: 0; color: var(--c-blue-deep); cursor: pointer; font: inherit; font-size: 12.5px; padding: 0; } .lk.red { color: var(--c-danger); }
.fm, .fm *, .fm2, .fm2 * { box-sizing: border-box; } .fm, .fm2 { display: flex; flex-direction: column; gap: 10px; } .g3 { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 10px; } .add { margin: 10px 0 6px; } label { display: flex; flex-direction: column; gap: 4px; font-size: 12.5px; color: var(--c-muted); }
input, select, textarea { font: inherit; font-size: 14px; padding: 7px 9px; border: 1px solid var(--c-rule-strong); background: #fff; width: 100%; min-width: 0; box-sizing: border-box; } input[type=file] { width: auto; } .row { display: flex; gap: 12px; align-items: center; margin-top: 8px; } .lnk { display: flex; gap: 12px; align-items: center; margin-top: 14px; flex-wrap: wrap; }
.st { font-size: 12px; padding: 2px 8px; background: var(--c-paper-2); } .st.paid { background: rgba(31,122,77,.1); color: var(--c-ok); } .st.due { background: rgba(181,71,8,.09); color: var(--c-warn); }
@media (max-width: 900px) { .g3 { grid-template-columns: 1fr; } }
</style>
