<script setup lang="ts">
// Money sent to companies from Credit, the Angel Fund and the venture fund, tied to the company, founder, fund and the
// books; Angel Fund money shows whether it came from Aidi or a named angel.
useHead({ title: 'Deployments & books' })
interface Opt { entities: { id: string; name: string }[]; funds: { id: string; name: string; structure: string; entity_id: string; currency: string }[]; loans: { id: string; borrower: string; reference: string | null; principal: number; currency: string; lender_entity_id: string | null }[]; applications: { id: string; company: string; contact_name: string | null; contact_email: string | null; amount: number; currency: string; terms: { lender_entity_id?: string } }[]; holdings: { id: string; name: string; entity_id: string | null; founder: { name?: string; email?: string } | null; currency: string }[]; angels: { id: string; name: string; email: string | null }[]; accounts: { id: string; name: string; entity_id: string; currency: string }[] }
interface Row { id: string; paid_on: string; source: string; entity: string | null; fund: string | null; loan_ref: string | null; holding: string | null; company: string; founder_name: string | null; amount: number; currency: string; instrument: string | null; reference: string | null; funded_by: { type: string; name?: string; amount: number }[]; notes: string | null }
const { data, refresh } = await useFetch<{ rows: Row[]; journal: { id: string; entry_date: string; account: string; debit: number; credit: number; currency: string; memo: string | null; entity: string | null }[]; balances: { entity: string | null; account: string; currency: string; balance: number }[]; options: Opt }>('/api/deployments')
const tab = ref<'deployments' | 'books'>('deployments')
const SRC: Record<string, string> = { credit: 'Credit (loan)', angel_fund: 'Angel Fund', venture_fund: 'Venture fund', other: 'Other' }
const money = (v: number, c: string) => new Intl.NumberFormat('en-US', { style: 'currency', currency: c, maximumFractionDigits: 0 }).format(v)
const blank = () => ({ open: false, paid_on: new Date().toISOString().slice(0, 10), source: 'angel_fund', paying_entity_id: '', fund_id: '', loan_id: '', application_id: '', holding_id: '', company: '', founder_name: '', founder_email: '', amount: 0, currency: 'USD', instrument: 'SAFE', reference: '', bank_account_id: '', notes: '', funded_by: [{ type: 'aidi', lp_id: '', amount: 0 }] as { type: string; lp_id: string; amount: number }[] })
const f = reactive(blank())
const route = useRoute()
onMounted(() => { const a = String(route.query.application ?? ''); if (a) { open(); f.source = 'credit'; f.application_id = a; pickApp() } })
function open() { Object.assign(f, blank(), { open: true }) }
const opt = computed(() => data.value?.options)
const funds = computed(() => (opt.value?.funds ?? []).filter((x) => (f.source === 'angel_fund' ? x.structure === 'rolling' : f.source === 'venture_fund' ? x.structure !== 'rolling' : true)))
function pickFund() { const fu = opt.value?.funds.find((x) => x.id === f.fund_id); if (fu) { f.paying_entity_id = fu.entity_id; f.currency = fu.currency } }
function pickApp() { const a = opt.value?.applications.find((x) => x.id === f.application_id); if (a) { f.company = a.company; f.founder_name = a.contact_name ?? ''; f.founder_email = a.contact_email ?? ''; f.amount = a.amount; f.currency = a.currency; f.instrument = 'Loan'; f.paying_entity_id = a.terms?.lender_entity_id ?? f.paying_entity_id; f.funded_by = [{ type: 'aidi', lp_id: '', amount: a.amount }] } }
function pickLoan() { const l = opt.value?.loans.find((x) => x.id === f.loan_id); if (l) { f.company = l.borrower; f.amount = l.principal; f.currency = l.currency; f.instrument = 'Loan'; f.paying_entity_id = l.lender_entity_id ?? f.paying_entity_id; f.funded_by = [{ type: 'aidi', lp_id: '', amount: l.principal }] } }
function pickHolding() { const h = opt.value?.holdings.find((x) => x.id === f.holding_id); if (h) { f.company = h.name; f.founder_name = h.founder?.name ?? ''; f.founder_email = h.founder?.email ?? ''; f.currency = h.currency } }
watch(() => f.amount, (v) => { if (f.funded_by.length === 1) f.funded_by[0]!.amount = Number(v) || 0 })
const fundedSum = computed(() => f.funded_by.reduce((s, x) => s + (Number(x.amount) || 0), 0))
const msg = ref(''); const busy = ref(false)
async function save() { busy.value = true; msg.value = ''
  try { await $fetch('/api/deployments', { method: 'POST', body: { ...f, open: undefined, amount: Number(f.amount), paying_entity_id: f.paying_entity_id || null, fund_id: f.fund_id || null, loan_id: f.loan_id || null, application_id: f.application_id || null, holding_id: f.holding_id || null, bank_account_id: f.bank_account_id || null, funded_by: f.funded_by.map((x) => ({ type: x.type, lp_id: x.lp_id || null, amount: Number(x.amount) })) } }); f.open = false; await refresh() }
  catch (e) { msg.value = (e as { data?: { data?: { error?: { message?: string } } } }).data?.data?.error?.message ?? 'Could not save.' } finally { busy.value = false } }
async function del(r: Row) { if (!confirm('Delete this deployment and its book entries? The loan or position it created stays; adjust those separately.')) return; await $fetch('/api/deployments', { method: 'POST', body: { delete_id: r.id } }); await refresh() }
const totals = computed(() => { const m: Record<string, Record<string, number>> = {}; for (const r of data.value?.rows ?? []) { (m[r.source] ??= {})[r.currency] = (m[r.source]![r.currency] ?? 0) + r.amount } return m })
const bal = computed(() => { const m = new Map<string, { entity: string; rows: { account: string; currency: string; balance: number }[] }>(); for (const b of data.value?.balances ?? []) { const k = b.entity ?? 'No entity'; if (!m.has(k)) m.set(k, { entity: k, rows: [] }); m.get(k)!.rows.push(b) } return [...m.values()] })
</script>
<template>
  <section v-if="data">
    <div class="hd"><div><p class="label">Family office</p><h1>Deployments &amp; books</h1><p class="lead">Every payment out of Credit, the Angel Fund and the venture fund: who paid, which company and founder received it, how it was funded, and the matching book entries.</p></div><button class="btn" @click="open">Log a deployment</button></div>
    <div class="kp"><div v-for="(v, s) in totals" :key="s" class="k"><span>{{ SRC[s] }}</span><b>{{ Object.entries(v).map(([c, a]) => money(a, c)).join(' · ') }}</b></div><div v-if="!data.rows.length" class="k"><span>Deployed</span><b>—</b></div></div>
    <nav class="tabs"><button :class="{ on: tab === 'deployments' }" @click="tab = 'deployments'">Deployments</button><button :class="{ on: tab === 'books' }" @click="tab = 'books'">Books</button></nav>
    <div v-if="tab === 'deployments'" class="card"><table class="table"><thead><tr><th>Date</th><th>Company · founder</th><th>From</th><th>Funded by</th><th class="n">Amount</th><th /></tr></thead><tbody>
      <tr v-for="r in data.rows" :key="r.id"><td>{{ r.paid_on }}</td><td><b>{{ r.company }}</b><span class="s">{{ [r.founder_name, r.instrument, r.reference].filter(Boolean).join(' · ') }}</span></td>
        <td>{{ SRC[r.source] }}<span class="s">{{ [r.fund, r.entity, r.loan_ref && 'loan ' + r.loan_ref].filter(Boolean).join(' · ') }}</span></td>
        <td><span v-for="(x, i) in r.funded_by" :key="i" class="fb">{{ x.type === 'aidi' ? 'Aidi' : x.name }} {{ money(x.amount, r.currency) }}</span></td><td class="n"><b>{{ money(r.amount, r.currency) }}</b></td><td><button class="lk" @click="del(r)">Delete</button></td></tr>
      <tr v-if="!data.rows.length"><td colspan="6" class="s">Nothing logged yet.</td></tr></tbody></table></div>
    <template v-else>
      <div class="bal"><div v-for="g in bal" :key="g.entity" class="card"><h3>{{ g.entity }}</h3><div v-for="r in g.rows" :key="r.account + r.currency" class="br"><span>{{ r.account }}</span><b :class="{ neg: r.balance < 0 }">{{ money(r.balance, r.currency) }}</b></div></div><p v-if="!bal.length" class="s">No entries yet.</p></div>
      <div class="card"><h3>Journal</h3><table class="table"><thead><tr><th>Date</th><th>Entity</th><th>Account</th><th class="n">Debit</th><th class="n">Credit</th><th>Memo</th></tr></thead><tbody>
        <tr v-for="j in data.journal" :key="j.id"><td>{{ j.entry_date }}</td><td>{{ j.entity ?? '—' }}</td><td>{{ j.account }}</td><td class="n">{{ j.debit ? money(j.debit, j.currency) : '' }}</td><td class="n">{{ j.credit ? money(j.credit, j.currency) : '' }}</td><td class="s">{{ j.memo }}</td></tr></tbody></table>
        <p class="s">Balances are debit minus credit. Each deployment posts Investments at cost (or Loans receivable) against Cash at bank on the paying entity; co-investments from angels post Cash at bank against Co-investor capital.</p></div>
    </template>
    <AppModal :open="f.open" title="Log a deployment" wide @close="f.open = false">
      <div class="fm"><div class="g3"><label class="label">Date paid<input v-model="f.paid_on" type="date"></label><label class="label">From<select v-model="f.source"><option value="angel_fund">Angel Fund</option><option value="venture_fund">Venture fund</option><option value="credit">Credit (loan)</option><option value="other">Other</option></select></label>
          <label v-if="f.source === 'angel_fund' || f.source === 'venture_fund'" class="label">Fund<select v-model="f.fund_id" @change="pickFund"><option value="">Choose</option><option v-for="x in funds" :key="x.id" :value="x.id">{{ x.name }}</option></select></label>
          <label v-if="f.source === 'credit'" class="label">Approved application<select v-model="f.application_id" @change="f.loan_id = ''; pickApp()"><option value="">None</option><option v-for="a in opt?.applications ?? []" :key="a.id" :value="a.id">{{ a.company }} · {{ money(a.amount, a.currency) }}</option></select></label></div>
        <div v-if="f.source === 'credit' && !f.application_id" class="g3"><label class="label">Existing loan<select v-model="f.loan_id" @change="pickLoan"><option value="">Choose</option><option v-for="l in opt?.loans ?? []" :key="l.id" :value="l.id">{{ l.borrower }}{{ l.reference ? ' · ' + l.reference : '' }} · {{ money(l.principal, l.currency) }}</option></select></label></div>
        <div v-if="f.source === 'angel_fund' || f.source === 'venture_fund'" class="g3"><label class="label">Company position<select v-model="f.holding_id" @change="pickHolding"><option value="">New position</option><option v-for="h in opt?.holdings ?? []" :key="h.id" :value="h.id">{{ h.name }}</option></select></label></div>
        <div class="g3"><label class="label">Company *<input v-model="f.company" maxlength="200"></label><label class="label">Founder<input v-model="f.founder_name" maxlength="200"></label><label class="label">Founder email<input v-model="f.founder_email" type="email" maxlength="254"></label>
          <label class="label">Amount *<input v-model.number="f.amount" type="number" min="0" step="0.01"></label><label class="label">Currency<select v-model="f.currency"><option>USD</option><option>NGN</option><option>GBP</option><option>EUR</option></select></label><label class="label">Instrument<select v-model="f.instrument"><option>SAFE</option><option>Equity</option><option>Convertible note</option><option>Loan</option><option>Other</option></select></label>
          <label class="label">Paid by (entity)<select v-model="f.paying_entity_id"><option value="">Choose</option><option v-for="e in opt?.entities ?? []" :key="e.id" :value="e.id">{{ e.name }}</option></select></label><label class="label">From bank account<select v-model="f.bank_account_id"><option value="">—</option><option v-for="a in (opt?.accounts ?? []).filter((x) => !f.paying_entity_id || x.entity_id === f.paying_entity_id)" :key="a.id" :value="a.id">{{ a.name }} ({{ a.currency }})</option></select></label><label class="label">Reference<input v-model="f.reference" maxlength="120" placeholder="Transfer ref."></label></div>
        <div class="fbx"><b>Funded by</b><span class="s">For the Angel Fund, split the amount between Aidi and the angels who put money in.</span>
          <div v-for="(x, i) in f.funded_by" :key="i" class="fr"><select v-model="x.type"><option value="aidi">Aidi (our money)</option><option value="angel">An angel</option></select><select v-if="x.type === 'angel'" v-model="x.lp_id"><option value="">Choose angel</option><option v-for="a in opt?.angels ?? []" :key="a.id" :value="a.id">{{ a.name }}</option></select><input v-model.number="x.amount" type="number" min="0" step="0.01"><button v-if="f.funded_by.length > 1" class="lk" @click="f.funded_by.splice(i, 1)">Remove</button></div>
          <button class="lk add" @click="f.funded_by.push({ type: 'angel', lp_id: '', amount: 0 })">+ Add a line</button><span :class="['s', { bad: Math.abs(fundedSum - Number(f.amount)) > 0.01 }]">Total {{ money(fundedSum, f.currency) }} of {{ money(Number(f.amount) || 0, f.currency) }}</span></div>
        <label class="label">Notes<textarea v-model="f.notes" rows="2" maxlength="3000" /></label><p v-if="msg" class="error">{{ msg }}</p></div>
      <template #foot><button class="btn secondary" @click="f.open = false">Cancel</button><button class="btn" :disabled="busy || !f.company || !f.amount" @click="save">{{ busy ? 'Saving…' : 'Log and post to the books' }}</button></template>
    </AppModal>
  </section>
</template>
<style scoped>
.hd { display: flex; justify-content: space-between; align-items: flex-end; gap: 12px; flex-wrap: wrap; } .hd h1 { margin: 0; } .lead { color: var(--c-muted); max-width: 760px; margin: 4px 0 0; }
.kp { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 12px; margin: 14px 0; } .k { background: #fff; border: 1px solid var(--c-rule); padding: 12px 14px; } .k span { display: block; font-size: 12.5px; color: var(--c-muted); } .k b { font-size: 20px; }
.tabs { display: flex; gap: 4px; background: var(--c-paper-2); padding: 4px; width: fit-content; margin-bottom: 12px; } .tabs button { background: none; border: 0; padding: 8px 14px; font: inherit; cursor: pointer; } .tabs .on { background: #fff; font-weight: 600; }
.n { text-align: right; white-space: nowrap; } .s { display: block; font-size: 12.5px; color: var(--c-muted); } .s.bad { color: var(--c-danger); } .fb { display: block; font-size: 12.5px; } .lk { background: none; border: 0; color: var(--c-blue-deep); cursor: pointer; font: inherit; font-size: 12.5px; padding: 0; }
.bal { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 12px; margin-bottom: 12px; } .bal h3 { margin: 0 0 6px; font-size: 15px; } .br { display: flex; justify-content: space-between; font-size: 13.5px; padding: 4px 0; border-top: 1px solid var(--c-rule); } .neg { color: var(--c-danger); }
.fm { display: flex; flex-direction: column; gap: 12px; } .g3 { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; } label.label { display: flex; flex-direction: column; gap: 5px; font-size: 12.5px; } input, select, textarea { font: inherit; font-size: 14px; padding: 7px 9px; border: 1px solid var(--c-rule-strong); background: #fff; }
.fbx { display: flex; flex-direction: column; gap: 6px; padding: 10px 12px; background: var(--c-paper-2); } .fr { display: flex; gap: 8px; align-items: center; } .fr input { width: 140px; } .add { align-self: flex-start; } .error { color: var(--c-danger); }
@media (max-width: 900px) { .g3 { grid-template-columns: 1fr; } }
</style>
