<script setup lang="ts">
// Payments out of the group: vendors, landlord, purchases… Each payment gets a voucher PDF and is posted to the books.
// Reconcile against an uploaded spreadsheet or balance sheet so the numbers stay true.
useHead({ title: 'Payments' })
interface Row { id: string; number: string; paid_on: string; payee: string; category: string; description: string | null; amount: number; currency: string; method: string | null; reference: string | null; voucher_id: string | null; attachment_id: string | null; entity: string | null; entity_id: string | null }
const { data, refresh } = await useFetch<{ rows: Row[]; options: { entities: { id: string; name: string }[]; accounts: { id: string; name: string; entity_id: string; currency: string }[]; categories: string[]; payees: string[] } }>('/api/expenses')
const money = (v: number, c: string) => new Intl.NumberFormat('en-US', { style: 'currency', currency: c, maximumFractionDigits: 2 }).format(v)
const q = ref(''); const ent = ref(''); const month = ref('')
const shown = computed(() => (data.value?.rows ?? []).filter((r) => (!ent.value || r.entity_id === ent.value) && (!month.value || r.paid_on.startsWith(month.value)) && (!q.value || (r.payee + ' ' + r.category + ' ' + (r.description ?? '') + ' ' + r.number).toLowerCase().includes(q.value.toLowerCase()))))
const totals = computed(() => { const m: Record<string, number> = {}; for (const r of shown.value) m[r.currency] = (m[r.currency] ?? 0) + r.amount; return m })
const byCat = computed(() => { const m = new Map<string, number>(); for (const r of shown.value.filter((x) => x.currency === (Object.keys(totals.value)[0] ?? 'USD'))) m.set(r.category, (m.get(r.category) ?? 0) + r.amount); return [...m.entries()].map(([label, value]) => ({ label, value })) })
const blank = () => ({ open: false, paid_on: new Date().toISOString().slice(0, 10), entity_id: '', payee: '', category: 'Software & subscriptions', description: '', amount: '' as string | number, currency: 'USD', method: 'Bank transfer', bank_account_id: '', reference: '' })
const f = reactive(blank()); const file = ref<File | null>(null); const msg = ref(''); const busy = ref(false); const dupe = ref('')
function open(prefill?: Partial<ReturnType<typeof blank>>) { Object.assign(f, blank(), prefill ?? {}, { open: true }); file.value = null; msg.value = ''; dupe.value = '' }
async function save(force = false) { busy.value = true; msg.value = ''; const fd = new FormData(); for (const [k, v] of Object.entries(f)) if (k !== 'open') fd.append(k, String(v)); if (force) fd.append('force', '1'); if (file.value) fd.append('file', file.value)
  try { await $fetch('/api/expenses', { method: 'POST', body: fd }); f.open = false; await refresh() } catch (e) { const er = e as { statusCode?: number; data?: { data?: { error?: { message?: string } } } }; if (er.statusCode === 409) dupe.value = er.data?.data?.error?.message ?? 'Possible duplicate.'; else msg.value = er.data?.data?.error?.message ?? 'Could not save.' } finally { busy.value = false } }
async function del(r: Row) { if (!confirm('Delete ' + r.number + ' (' + r.payee + ')? Its book entries are removed; the voucher PDF stays in Documents.')) return; const fd = new FormData(); fd.append('delete_id', r.id); await $fetch('/api/expenses', { method: 'POST', body: fd }); await refresh() }
// reconciliation
interface Rec { summary: string; sheet_kind: string; totals: { logged: number; sheet: number; difference: number; currency: string }; matched: { log_number: string; sheet_row: string; note?: string }[]; missing_in_log: { date: string; payee: string; amount: number; currency: string; category?: string; sheet_row: string }[]; missing_in_sheet: { log_number: string; note?: string }[]; mismatched: { log_number: string; sheet_row: string; issue: string }[]; category_checks: { category: string; logged: number; sheet: number; note?: string }[] }
const rc = reactive({ open: false, from: new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10), to: new Date().toISOString().slice(0, 10), entity_id: '', busy: false, msg: '' }); const rfile = ref<File | null>(null); const rec = ref<Rec | null>(null)
async function reconcile() { if (!rfile.value) return; rc.busy = true; rc.msg = ''; rec.value = null; const fd = new FormData(); fd.append('file', rfile.value); fd.append('from', rc.from); fd.append('to', rc.to); fd.append('entity_id', rc.entity_id)
  try { rec.value = await $fetch<Rec>('/api/expenses/reconcile', { method: 'POST', body: fd }) } catch (e) { rc.msg = (e as { data?: { data?: { error?: { message?: string } } } }).data?.data?.error?.message ?? 'Could not reconcile. Check the file and try again.' } finally { rc.busy = false } }
</script>
<template>
  <section v-if="data">
    <div class="hd"><div><p class="label">Financials</p><h1>Payments</h1><p class="lead">Log what the group pays out: vendors, rent, purchases, fees. Each payment gets a voucher PDF, is posted to the journals, and can be reconciled against your spreadsheets.</p></div>
      <div class="acts"><button class="btn secondary" @click="rc.open = true; rec = null">Reconcile with a spreadsheet</button><button class="btn" @click="open()">Log a payment</button></div></div>
    <div class="kp"><div class="k"><span>Total in view</span><b>{{ Object.keys(totals).length ? Object.entries(totals).map(([c, v]) => money(v, c)).join(' · ') : '—' }}</b><em>{{ shown.length }} payment{{ shown.length === 1 ? '' : 's' }}</em></div>
      <div v-if="byCat.length" class="k wide"><DonutChart title="By category" total-label="Total" :currency="Object.keys(totals)[0]" :segments="byCat" /></div></div>
    <div class="flt"><input v-model="q" placeholder="Search payee, category, voucher no."><select v-model="ent"><option value="">All entities</option><option v-for="e in data.options.entities" :key="e.id" :value="e.id">{{ e.name }}</option></select><input v-model="month" type="month"></div>
    <div class="card tc"><table v-if="shown.length" class="table"><thead><tr><th>Date</th><th>Voucher</th><th>Paid to</th><th>Category</th><th>Entity</th><th class="n">Amount</th><th>Records</th><th /></tr></thead><tbody>
      <tr v-for="r in shown" :key="r.id"><td>{{ r.paid_on }}</td><td>{{ r.number }}</td><td><b>{{ r.payee }}</b><span v-if="r.description" class="s">{{ r.description }}</span></td><td>{{ r.category }}</td><td>{{ r.entity ?? '—' }}</td><td class="n"><b>{{ money(r.amount, r.currency) }}</b><span class="s">{{ [r.method, r.reference].filter(Boolean).join(' · ') }}</span></td>
        <td><a v-if="r.voucher_id" :href="'/api/expenses/doc/' + r.voucher_id" target="_blank">Voucher</a><a v-if="r.attachment_id" :href="'/api/expenses/doc/' + r.attachment_id" target="_blank" class="ml">Invoice</a></td><td><button class="lk" @click="del(r)">Delete</button></td></tr></tbody></table>
      <EmptyState v-else compact icon="billing" title="No payments logged" text="Log rent, vendor bills, software and purchases. Each one gets a voucher and is posted to the books."><button class="btn" @click="open()">Log a payment</button></EmptyState></div>
    <AppModal :open="f.open" title="Log a payment" wide @close="f.open = false">
      <div class="fm"><div class="g3"><label class="label">Date paid<input v-model="f.paid_on" type="date"></label><label class="label">Paid by (entity)<select v-model="f.entity_id"><option value="">Choose</option><option v-for="e in data.options.entities" :key="e.id" :value="e.id">{{ e.name }}</option></select></label><label class="label">Category<select v-model="f.category"><option v-for="c in data.options.categories" :key="c">{{ c }}</option></select></label>
          <label class="label">Paid to *<input v-model="f.payee" list="payees" maxlength="200" placeholder="Vendor, landlord, supplier"><datalist id="payees"><option v-for="p in data.options.payees" :key="p" :value="p" /></datalist></label><label class="label">Amount *<input v-model="f.amount" type="number" min="0" step="0.01"></label><label class="label">Currency<select v-model="f.currency"><option>USD</option><option>NGN</option><option>GBP</option><option>EUR</option></select></label>
          <label class="label">Method<select v-model="f.method"><option>Bank transfer</option><option>Card</option><option>Cash</option><option>Cheque</option><option>Direct debit</option><option>Other</option></select></label><label class="label">From account<select v-model="f.bank_account_id"><option value="">—</option><option v-for="a in data.options.accounts.filter((x) => !f.entity_id || x.entity_id === f.entity_id)" :key="a.id" :value="a.id">{{ a.name }} ({{ a.currency }})</option></select></label><label class="label">Reference<input v-model="f.reference" maxlength="120" placeholder="Transfer ref., invoice no."></label></div>
        <label class="label">What it was for<textarea v-model="f.description" rows="2" maxlength="3000" /></label>
        <label class="label">Invoice or receipt (optional)<DropZone compact accept=".pdf,image/png,image/jpeg,image/webp" @change="file = ($event.target as HTMLInputElement).files?.[0] ?? null" /></label>
        <p class="s">A payment voucher (PDF) is created and kept in Documents, and the payment is posted to the books as an expense against cash at bank.</p>
        <p v-if="dupe" class="dup">{{ dupe }} <button class="lk" @click="save(true)">Save anyway</button></p><p v-if="msg" class="error">{{ msg }}</p></div>
      <template #foot><button class="btn secondary" @click="f.open = false">Cancel</button><button class="btn" :disabled="busy || !f.payee || !f.amount" @click="save()">{{ busy ? 'Saving…' : 'Log payment and create voucher' }}</button></template>
    </AppModal>
    <AppModal :open="rc.open" title="Reconcile with a spreadsheet" wide @close="rc.open = false">
      <div class="fm"><p class="s">Upload a bank export, ledger, expense report, or a balance sheet / P&amp;L (Excel or CSV). AI compares it with the payments logged for the period and shows what matches, what is missing on either side, and any differences, so the books are not distorted.</p>
        <div class="g3"><label class="label">From<input v-model="rc.from" type="date"></label><label class="label">To<input v-model="rc.to" type="date"></label><label class="label">Entity<select v-model="rc.entity_id"><option value="">All entities</option><option v-for="e in data.options.entities" :key="e.id" :value="e.id">{{ e.name }}</option></select></label></div>
        <label class="label">Spreadsheet<DropZone compact accept=".xlsx,.csv" @change="rfile = ($event.target as HTMLInputElement).files?.[0] ?? null" /></label>
        <p v-if="rc.msg" class="error">{{ rc.msg }}</p>
        <div v-if="rec" class="rec"><p class="sum"><b>{{ rec.sheet_kind }}</b> · {{ rec.summary }}</p>
          <div class="rt"><span>Logged <b>{{ money(rec.totals.logged, rec.totals.currency || 'USD') }}</b></span><span>Sheet <b>{{ money(rec.totals.sheet, rec.totals.currency || 'USD') }}</b></span><span :class="{ bad: Math.abs(rec.totals.difference) > 0.01 }">Difference <b>{{ money(rec.totals.difference, rec.totals.currency || 'USD') }}</b></span></div>
          <h4 v-if="rec.missing_in_log.length">In the sheet but not logged ({{ rec.missing_in_log.length }})</h4><div v-for="(m, i) in rec.missing_in_log" :key="'m' + i" class="ri"><span>{{ m.date }} · {{ m.payee }} · {{ money(m.amount, m.currency || 'USD') }} <em>{{ m.sheet_row }}</em></span><button class="lk" @click="rc.open = false; open({ paid_on: m.date, payee: m.payee, amount: m.amount, currency: m.currency || 'USD', category: m.category && data.options.categories.includes(m.category) ? m.category : 'Other' })">Log it</button></div>
          <h4 v-if="rec.mismatched.length">Differences ({{ rec.mismatched.length }})</h4><div v-for="(m, i) in rec.mismatched" :key="'x' + i" class="ri"><span>{{ m.log_number }} ↔ {{ m.sheet_row }}: {{ m.issue }}</span></div>
          <h4 v-if="rec.missing_in_sheet.length">Logged but not in the sheet ({{ rec.missing_in_sheet.length }})</h4><div v-for="(m, i) in rec.missing_in_sheet" :key="'s' + i" class="ri"><span>{{ m.log_number }}{{ m.note ? ': ' + m.note : '' }}</span></div>
          <h4 v-if="rec.category_checks.length">By category</h4><div v-for="(c, i) in rec.category_checks" :key="'c' + i" class="ri"><span>{{ c.category }}: logged {{ money(c.logged, rec.totals.currency || 'USD') }}, sheet {{ money(c.sheet, rec.totals.currency || 'USD') }}{{ c.note ? ' · ' + c.note : '' }}</span></div>
          <p class="s">{{ rec.matched.length }} payment{{ rec.matched.length === 1 ? '' : 's' }} matched.</p></div></div>
      <template #foot><button class="btn secondary" @click="rc.open = false">Close</button><button class="btn" :disabled="rc.busy || !rfile" @click="reconcile">{{ rc.busy ? 'Reconciling…' : 'Reconcile' }}</button></template>
    </AppModal>
  </section>
</template>
<style scoped>
.hd { display: flex; justify-content: space-between; align-items: flex-end; gap: 12px; flex-wrap: wrap; } .hd h1 { margin: 0; } .lead { color: var(--c-muted); max-width: 760px; margin: 4px 0 0; } .acts { display: flex; gap: 8px; }
.kp { display: grid; grid-template-columns: 260px minmax(0, 1fr); gap: 12px; margin: 14px 0; } .k { background: #fff; border: 1px solid var(--c-rule); padding: 12px 14px; } .k span { display: block; font-size: 12.5px; color: var(--c-muted); } .k b { font-size: 20px; } .k em { display: block; font-style: normal; font-size: 12px; color: var(--c-muted); }
.flt { display: flex; gap: 8px; margin-bottom: 10px; flex-wrap: wrap; } .flt input, .flt select { font: inherit; font-size: 13.5px; padding: 7px 9px; border: 1px solid var(--c-rule-strong); }
.tc { padding: 0; overflow-x: auto; } .table { width: 100%; border-collapse: collapse; font-size: 13.5px; } .table th { text-align: left; padding: 10px 14px; white-space: nowrap; } .table td { padding: 11px 14px; border-bottom: 1px solid var(--c-rule); vertical-align: top; } .n { text-align: right; white-space: nowrap; }
.s { display: block; font-size: 12.5px; color: var(--c-muted); margin: 0; } .lk { background: none; border: 0; color: var(--c-blue-deep); cursor: pointer; font: inherit; font-size: 12.5px; padding: 0; } .ml { margin-left: 8px; } td a { color: var(--c-blue-deep); font-size: 13px; }
.fm, .fm * { box-sizing: border-box; } .fm { display: flex; flex-direction: column; gap: 12px; } .g3 { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 10px; } label.label { display: flex; flex-direction: column; gap: 5px; font-size: 12.5px; } .fm input, .fm select, .fm textarea { font: inherit; font-size: 14px; padding: 7px 9px; border: 1px solid var(--c-rule-strong); background: #fff; width: 100%; min-width: 0; }
.dup { background: #fff7ea; border-left: 3px solid #e3a008; padding: 8px 12px; font-size: 13px; margin: 0; } .error { color: var(--c-danger); }
.rec { display: flex; flex-direction: column; gap: 6px; border-top: 1px solid var(--c-rule); padding-top: 10px; } .sum { margin: 0; font-size: 14px; } .rt { display: flex; gap: 18px; flex-wrap: wrap; font-size: 13.5px; } .rt .bad { color: var(--c-danger); } .rec h4 { margin: 10px 0 2px; font-size: 13.5px; } .ri { display: flex; justify-content: space-between; gap: 10px; font-size: 13px; padding: 4px 0; border-top: 1px solid var(--c-rule); } .ri em { font-style: normal; color: var(--c-muted); }
@media (max-width: 900px) { .g3, .kp { grid-template-columns: 1fr; } }
</style>
