// SAFE documents drafted from the agreed terms: the SAFE itself (post-money structure: cap, discount, cap + discount or
// MFN only), an MFN side letter and a pro rata side letter. Finvry's own wording following the standard post-money
// SAFE structure. Not legal advice.
export interface SafeRow { company_name: string; company_state: string; investor_name: string; investor_email: string | null; amount: number; currency: string; valuation_cap: number | null; discount: number | null; mfn: boolean; pro_rata: boolean; signatory_name: string; signatory_title: string; safe_date: string }
export interface SafeDoc { key: 'safe' | 'mfn' | 'pro_rata'; title: string; md: string }
const SYM: Record<string, string> = { USD: '$', NGN: 'NGN ' }
export function safeDocs(s: SafeRow): SafeDoc[] {
  const money = (v: number) => (SYM[s.currency] ?? s.currency + ' ') + Number(v).toLocaleString('en-US', { maximumFractionDigits: 2 })
  const date = new Date(s.safe_date + 'T00:00:00Z').toLocaleDateString('en-US', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' })
  const kind = /llc/i.test(s.company_name) ? 'company' : 'corporation'
  const cap = s.valuation_cap ? money(s.valuation_cap) : null
  const rate = s.discount ? (100 - s.discount) + '%' : null
  const variant = cap && rate ? 'Valuation Cap and Discount' : cap ? 'Valuation Cap, no Discount' : rate ? 'Discount, no Valuation Cap' : 'MFN Only, no Valuation Cap, no Discount'
  const mfnOnly = !cap && !rate
  const note = '> Prepared with Finvry from the terms agreed between the parties, following the standard post-money SAFE structure. This is not legal advice. Each party should have the documents reviewed by its own counsel before signing.'
  const sigs = (left: string, right: string) => [
    '## Signatures', '',
    '**' + left + '**', '', s.company_name, '', 'By: ______________________________', '', 'Name: ' + s.signatory_name, '', 'Title: ' + s.signatory_title, '', 'Date: ______________________________', '',
    '**' + right + '**', '', s.investor_name, '', 'By: ______________________________', '', 'Name: ______________________________', '', 'Title: ______________________________', '', 'Email: ' + (s.investor_email || '______________________________'), '', 'Date: ______________________________']
  const safe: string[] = [
    '# SAFE (Simple Agreement for Future Equity)', '', '**' + variant + '**', '', note, '',
    'THIS INSTRUMENT AND ANY SECURITIES ISSUABLE UNDER IT HAVE NOT BEEN REGISTERED UNDER THE SECURITIES ACT OF 1933, AS AMENDED, OR THE SECURITIES LAWS OF ANY STATE OR OTHER JURISDICTION. THEY MAY NOT BE SOLD, PLEDGED OR OTHERWISE TRANSFERRED EXCEPT AS ALLOWED UNDER THAT ACT AND THOSE LAWS.', '',
    'In return for **' + s.investor_name + '** (the "Investor") paying **' + money(s.amount) + '** (the "Purchase Amount") on or about **' + date + '**, **' + s.company_name + '**, a ' + s.company_state + ' ' + kind + ' (the "Company"), grants the Investor the right to receive shares of the Company\'s Capital Stock on the terms set out in this agreement (this "Safe").', '',
    ...(cap ? ['**Post-Money Valuation Cap:** ' + cap, ''] : []),
    ...(rate ? ['**Discount Rate:** ' + rate + ' (a ' + s.discount + '% discount to the price paid by new investors)', ''] : []),
    ...(mfnOnly ? ['**Conversion:** this Safe has no valuation cap and no discount. It converts at the price paid by new investors in the Equity Financing and carries the Most Favored Nation right in Section 5.', ''] : []),
    'Capitalised terms are defined in Section 2.', '',
    '## 1. Events', '',
    '**(a) Equity Financing.** If there is an Equity Financing before this Safe ends, this Safe will automatically convert, at the first closing of that Equity Financing, into the number of shares of Safe Preferred Stock equal to the Purchase Amount divided by the Conversion Price. To receive those shares the Investor will sign the same transaction documents that the other investors in the Equity Financing sign, with any changes that are reasonable for the Safe Preferred Stock. The Safe Preferred Stock will have the same rights as the Standard Preferred Stock, except that its liquidation preference per share and any price-based adjustment will be based on the Conversion Price instead of the price paid for the Standard Preferred Stock.', '',
    '**(b) Liquidity Event.** If there is a Liquidity Event before this Safe ends, the Investor will be automatically entitled to receive, out of the Proceeds and immediately before or at the same time as the Liquidity Event, the greater of (i) the Purchase Amount (the "Cash-Out Amount") and (ii) the amount payable on the number of shares of Common Stock equal to the Purchase Amount divided by the Liquidity Price (the "Conversion Amount"). If the Proceeds are not enough to pay the Investor and the holders of other Safes and Preferred Stock their cash-out amounts in full, the available Proceeds will be paid to them pro rata in proportion to those amounts. If a Liquidity Event is intended to qualify as a tax-free reorganisation, the Company may reduce the cash part of the Proceeds payable to the Investor to the extent needed for that treatment, with the balance paid in the same form as the consideration paid to Common Stock holders.', '',
    '**(c) Dissolution Event.** If there is a Dissolution Event before this Safe ends, the Investor will be automatically entitled to receive the Purchase Amount, paid before any distribution to holders of Common Stock, as described in Section 1(d).', '',
    '**(d) Liquidation priority.** In a Liquidity Event or Dissolution Event, the Investor\'s right to receive its Cash-Out Amount or Purchase Amount is (i) junior to payment of the Company\'s debt and other liabilities and creditor claims; (ii) on a par with payments on other Safes and Preferred Stock, and if there are not enough assets to pay these in full, the assets will be shared among them pro rata in proportion to the amounts due; and (iii) senior to payments on Common Stock. A right to receive a Conversion Amount ranks with the Common Stock.', '',
    '**(e) End of this Safe.** This Safe ends, and has no further effect, on the earlier of (i) the issue of Capital Stock to the Investor under Section 1(a); and (ii) the payment, or setting aside of the payment, of amounts due to the Investor under Section 1(b) or 1(c).', '',
    '## 2. Definitions', '',
    '"**Capital Stock**" means the capital stock of the Company, including the Common Stock and the Preferred Stock (or, if the Company is a limited liability company, its equivalent membership interests).', '',
    '"**Change of Control**" means (i) a transaction in which any person or group becomes the owner, directly or indirectly, of more than 50% of the outstanding voting securities of the Company with the right to elect a majority of its directors; (ii) a merger or consolidation of the Company, unless the Company\'s voting securities before the transaction still represent more than 50% of the voting power of the surviving entity afterwards; or (iii) a sale, lease or other disposal of all or substantially all of the Company\'s assets.', '',
    '"**Common Stock**" means the Company\'s common stock (or common units).', '',
    '"**Company Capitalization**" means, immediately before the Equity Financing and calculated on an as-converted basis, the sum of (i) all shares of Capital Stock issued and outstanding; (ii) all Converting Securities, including this Safe; (iii) all issued and outstanding options and warrants; and (iv) all shares reserved and available for future grant under any equity incentive plan, including any increase made in connection with the Equity Financing. It excludes the shares of Standard Preferred Stock issued for new money in the Equity Financing.', '',
    '"**Conversion Price**" means ' + (cap && rate ? 'the lower of the Safe Price and the Discount Price.' : cap ? 'the Safe Price.' : rate ? 'the Discount Price.' : 'the price per share of the Standard Preferred Stock.'), '',
    '"**Converting Securities**" means this Safe and other convertible securities issued by the Company, including other Safes, convertible notes and similar instruments.', '',
    ...(rate ? ['"**Discount Price**" means the price per share of the Standard Preferred Stock multiplied by the Discount Rate.', ''] : []),
    '"**Dissolution Event**" means (i) a voluntary end of operations; (ii) a general assignment for the benefit of the Company\'s creditors; or (iii) any other liquidation, dissolution or winding up of the Company, whether voluntary or not, other than a Liquidity Event.', '',
    '"**Equity Financing**" means a bona fide transaction or series of transactions with the principal purpose of raising capital, in which the Company issues and sells Preferred Stock at a fixed valuation, including a pre-money or post-money valuation.', '',
    '"**Initial Public Offering**" means the closing of the Company\'s first firm commitment underwritten public offering of Common Stock, or a direct listing or similar listing of the Company\'s securities on a recognised stock exchange.', '',
    ...(cap ? ['"**Liquidity Capitalization**" means, immediately before the Liquidity Event and calculated on an as-converted basis, the number of shares of Capital Stock outstanding plus all Converting Securities, options and warrants (vested or not) and shares reserved under any equity incentive plan, excluding any reserved shares that are not subject to issued awards.', ''] : []),
    '"**Liquidity Event**" means a Change of Control or an Initial Public Offering.', '',
    '"**Liquidity Price**" means ' + (cap ? 'the Post-Money Valuation Cap divided by the Liquidity Capitalization.' : 'the fair market value of the Common Stock at the time of the Liquidity Event, as determined by reference to the purchase price paid in the Liquidity Event.'), '',
    '"**Preferred Stock**" means the Company\'s preferred stock (or preferred units).', '',
    '"**Proceeds**" means cash and other assets, including stock, that are proceeds from the Liquidity Event and available for distribution.', '',
    ...(cap ? ['"**Safe Price**" means the Post-Money Valuation Cap divided by the Company Capitalization.', ''] : []),
    '"**Safe Preferred Stock**" means the shares of the series of Preferred Stock issued to the Investor in an Equity Financing, having the rights, privileges, preferences and restrictions of the Standard Preferred Stock, adjusted as described in Section 1(a).', '',
    '"**Standard Preferred Stock**" means the shares of the series of Preferred Stock issued to the investors investing new money in the Company in connection with the first closing of the Equity Financing.', '',
    '## 3. Company representations', '',
    '**(a)** The Company is duly organised, validly existing and in good standing under the laws of its state of incorporation, and has the power and authority to own, lease and operate its properties and carry on its business as now conducted.', '',
    '**(b)** Signing, delivering and performing this Safe is within the Company\'s power and has been duly authorised by all necessary actions on its part. This Safe is a legal, valid and binding obligation of the Company, enforceable in accordance with its terms, except as limited by bankruptcy, insolvency and similar laws and by general principles of equity.', '',
    '**(c)** Performing this Safe does not and will not violate any material law, the Company\'s governing documents, or any material agreement, judgment or order to which the Company is a party or bound, and will not create any lien on the Company\'s assets.', '',
    '**(d)** No consent or approval of any person or governmental authority is needed for the Company to perform this Safe, other than qualifications or filings under securities laws, and approvals already obtained.', '',
    '**(e)** To its knowledge, the Company owns or has the right to use the intellectual property it needs to run its business as now conducted, without any conflict with the rights of others.', '',
    '## 4. Investor representations', '',
    '**(a)** The Investor has full legal capacity, power and authority to sign and perform this Safe. This Safe is a valid and binding obligation of the Investor.', '',
    '**(b)** The Investor is an accredited investor as defined in Rule 501 of Regulation D under the Securities Act (or, if outside the United States, is acquiring this Safe in compliance with the laws of its jurisdiction). The Investor is acquiring this Safe and any securities issuable under it for its own account, for investment and not with a view to distribution.', '',
    '**(c)** The Investor understands that this Safe and the underlying securities have not been registered, may not be resold without registration or an exemption, and that the Investor may lose its entire investment. The Investor has had the chance to ask questions of the Company and has the knowledge and experience to evaluate the merits and risks of this investment.', '',
    ...(mfnOnly ? [
      '## 5. Most Favored Nation', '',
      'If, after this Safe is issued and before it ends, the Company issues any Subsequent Convertible Securities with terms more favourable to the holder than the terms of this Safe (for example a valuation cap, a discount, or more favourable conversion or payment terms), the Company will promptly give the Investor written notice of those securities and their terms, with copies of the documents. If the Investor chooses, by written notice to the Company within 30 days of receiving that notice, this Safe will be amended to have the same terms as those Subsequent Convertible Securities, except for the purchase amount and any terms that apply only to the other holder. "**Subsequent Convertible Securities**" means Safes and other convertible securities issued by the Company after this Safe for the principal purpose of raising capital, excluding options under equity incentive plans and securities issued in an Equity Financing.', ''] : []),
    '## ' + (mfnOnly ? '6' : '5') + '. Miscellaneous', '',
    '**(a) Amendments.** A term of this Safe may be amended or waived with the written consent of the Company and the Investor. Any amendment or waiver made with the written consent of the Company and holders of a majority in purchase amount of the Safes of this series that are then outstanding binds all holders of those Safes, provided it applies to all of them in the same way.', '',
    '**(b) Notices.** Notices under this Safe must be in writing and are given when delivered personally, sent by email to the address shown on the signature page (or later updated in writing), or one business day after being sent by a nationally recognised courier.', '',
    '**(c) No shareholder rights.** The Investor is not, by holding this Safe, entitled to vote, receive dividends or exercise any other rights of a holder of Capital Stock until shares have been issued to it under this Safe.', '',
    '**(d) Transfer.** Neither this Safe nor the rights in it may be transferred by either party without the other party\'s written consent, except that the Investor may transfer this Safe to an affiliate, and the Company may assign it in a reincorporation that changes its domicile.', '',
    '**(e) Not debt.** This Safe is not a loan. It carries no interest and has no maturity date. The parties intend it to be treated as stock for US federal and state income tax purposes and will not take a contrary position unless required by law.', '',
    '**(f) Severability.** If any provision of this Safe is held invalid, illegal or unenforceable, the rest of this Safe stays in effect.', '',
    '**(g) Governing law.** This Safe is governed by the laws of the State of ' + (s.company_state === 'Other' ? 'Delaware' : s.company_state) + ', without regard to its conflict of laws rules.', '',
    '**(h) Counterparts and electronic signatures.** This Safe may be signed in counterparts, each of which is an original, and by electronic signature, which has the same effect as a handwritten one.', '',
    ...sigs('Company', 'Investor')]
  const docs: SafeDoc[] = [{ key: 'safe', title: 'SAFE: ' + s.investor_name, md: safe.join('\n') }]
  if (s.mfn && !mfnOnly) docs.push({ key: 'mfn', title: 'MFN Side Letter: ' + s.investor_name, md: [
    '# Most Favored Nation Side Letter', '', note, '', date, '',
    'To: **' + s.investor_name + '**' + (s.investor_email ? ' (' + s.investor_email + ')' : ''), '',
    'This letter is given in connection with the SAFE dated ' + date + ' between **' + s.company_name + '** (the "Company") and you (the "Investor") for a purchase amount of ' + money(s.amount) + ' (the "Safe"). Terms defined in the Safe have the same meaning here.', '',
    '**1. Most Favored Nation right.** If, after the Safe is issued and before it ends, the Company issues any Subsequent Convertible Securities on terms more favourable to the holder than the terms of the Safe (for example a lower valuation cap, a larger discount, or more favourable conversion or payment terms), the Company will promptly tell the Investor in writing and provide the terms and documents.', '',
    '**2. Election.** The Investor may, by written notice to the Company within 30 days of receiving that notice, choose to amend the Safe so that it has the same terms as those Subsequent Convertible Securities, except for the purchase amount and any terms that apply only to the other holder. The Company and the Investor will sign any documents reasonably needed to make that amendment.', '',
    '**3. Definitions.** "Subsequent Convertible Securities" means Safes and other convertible securities issued by the Company after the Safe for the principal purpose of raising capital, excluding options under equity incentive plans and securities issued in an Equity Financing.', '',
    '**4. Term.** This letter ends when the Safe ends. It is part of the Safe and is governed by the same law. It may be amended only in writing signed by both parties.', '',
    ...sigs('Agreed: Company', 'Accepted: Investor')].join('\n') })
  if (s.pro_rata) docs.push({ key: 'pro_rata', title: 'Pro Rata Side Letter: ' + s.investor_name, md: [
    '# Pro Rata Rights Side Letter', '', note, '', date, '',
    'To: **' + s.investor_name + '**' + (s.investor_email ? ' (' + s.investor_email + ')' : ''), '',
    'This letter is given in connection with the SAFE dated ' + date + ' between **' + s.company_name + '** (the "Company") and you (the "Investor") for a purchase amount of ' + money(s.amount) + ' (the "Safe"). Terms defined in the Safe have the same meaning here.', '',
    '**1. Pro rata right.** In the Equity Financing in which the Safe converts, the Investor may buy, on the same terms as the other investors in that Equity Financing, up to its Pro Rata Portion of the Standard Preferred Stock offered in that financing.', '',
    '**2. Pro Rata Portion.** The "Pro Rata Portion" is the number of shares of Standard Preferred Stock equal to the total number of shares of Standard Preferred Stock offered in the Equity Financing multiplied by a fraction: the number of shares of Capital Stock the Investor receives on conversion of the Safe, divided by the Company\'s fully diluted capitalisation immediately after the conversion of all Converting Securities and before the issue of new money shares.' + (cap ? ' For illustration, at the Post-Money Valuation Cap of ' + cap + ' the Investor\'s ownership from the Safe would be about ' + (Math.round((s.amount / s.valuation_cap!) * 10000) / 100) + '%.' : ''), '',
    '**3. Exercise.** The Company will give the Investor reasonable written notice of the Equity Financing and its terms. The Investor may exercise this right by written notice and payment on or before the closing of the Equity Financing. If it does not, the right lapses for that financing.', '',
    '**4. Exclusions.** This right does not apply to securities issued under equity incentive plans, on conversion of convertible securities, in acquisitions, to lenders or equipment lessors, or in a registered public offering.', '',
    '**5. Term.** This right ends immediately after the first closing of the Equity Financing in which the Safe converts, or on the earlier end of the Safe. This letter is governed by the same law as the Safe, may be amended only in writing signed by both parties, and may not be assigned by the Investor except with the Safe.', '',
    ...sigs('Agreed: Company', 'Accepted: Investor')].join('\n') })
  return docs
}
